import { auth, db } from "./firebase.js";
import { formatMoney, getMoneyValue, resetMoneyField, setMoneyValue } from "./money.js";
import { addDoc, collection, deleteDoc, doc, getDocs, onSnapshot, orderBy, query, serverTimestamp, updateDoc } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";

const content=document.getElementById("content"),placeholder=document.getElementById("placeholderView");
let view=document.getElementById("cartoes");if(view)view.remove();
view=document.createElement("div");view.id="cartoes";view.className="app-view hidden";
view.innerHTML=`<div class="page-grid card-layout"><article class="panel"><h3 id="cardFormTitle">Novo cartão</h3><form id="cardForm" class="account-form"><label>Nome do cartão</label><input id="cardNome" maxlength="60" placeholder="Ex.: Visa BTG" required><label>Conta vinculada</label><select id="cardConta" required></select><label>Bandeira</label><select id="cardBandeira"><option>Visa</option><option>Mastercard</option><option>Elo</option><option>American Express</option><option>Hipercard</option><option>Outra</option></select><label>Moeda</label><select id="cardMoeda" required></select><label>Limite</label><div class="money-field" data-money-field><div class="money-input-row"><select id="cardMoedaMirror" data-money-currency disabled></select><input id="cardLimite" data-money-input type="text" inputmode="decimal" value="0,00"><button type="button" class="calculator-toggle" data-money-calculator>🧮</button></div></div><label>Dia de fechamento</label><input id="cardFechamento" type="number" min="1" max="31" required><label>Dia de vencimento</label><input id="cardVencimento" type="number" min="1" max="31" required><button id="cardSalvar" class="primary form-button" type="submit">Salvar cartão</button><button id="cardCancelar" class="secondary form-button hidden" type="button">Cancelar edição</button><p id="cardMensagem" class="message"></p></form></article><article class="panel"><h3>Meus cartões</h3><div id="listaCartoes"><div class="empty-state">Nenhum cartão cadastrado.</div></div></article></div>`;
content.insertBefore(view,placeholder);

const style=document.createElement("style");style.textContent=`.card-layout{grid-template-columns:minmax(300px,380px) minmax(0,1fr)}.credit-card-item{padding:16px;border:1px solid var(--border);border-radius:13px;margin-bottom:12px;background:#fafcff}.credit-card-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.credit-card-meta{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-top:12px}.credit-card-meta div{padding:10px;border-radius:9px;background:white;border:1px solid var(--border)}.credit-card-meta span{display:block;color:var(--muted);font-size:.78rem}.credit-card-actions{display:flex;gap:8px}.credit-card-actions button{border:0;background:transparent}.edit-card{color:var(--primary)}.delete-card{color:var(--danger)}@media(max-width:980px){.card-layout{grid-template-columns:1fr}}@media(max-width:520px){.credit-card-meta{grid-template-columns:1fr}}`;document.head.appendChild(style);

const $=id=>document.getElementById(id);const form=$("cardForm"),title=$("cardFormTitle"),account=$("cardConta"),currency=$("cardMoeda"),currencyMirror=$("cardMoedaMirror"),limitInput=$("cardLimite"),list=$("listaCartoes"),message=$("cardMensagem"),save=$("cardSalvar"),cancel=$("cardCancelar");
let user=null,accounts=[],cards=[],editing=null,stop=null;
const esc=(v="")=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]);
async function accountCurrencies(item){const snap=await getDocs(collection(db,"users",user.uid,"contas",item.id,"moedas"));return [...new Set([item.moeda||"BRL",...snap.docs.map(d=>d.data().codigo)])];}
async function refreshCurrencies(preferred=""){const acc=accounts.find(a=>a.id===account.value);if(!acc){currency.innerHTML="";currencyMirror.innerHTML="";return;}const values=await accountCurrencies(acc);currency.innerHTML=values.map(v=>`<option value="${v}">${v}</option>`).join("");if(preferred&&values.includes(preferred))currency.value=preferred;currencyMirror.innerHTML=`<option value="${currency.value}">${currency.value}</option>`;}
function renderAccounts(){account.innerHTML=`<option value="">Selecione...</option>${accounts.map(a=>`<option value="${a.id}">${esc(a.nome)}</option>`).join("")}`;}
function render(){list.innerHTML=cards.length?cards.map(c=>`<article class="credit-card-item"><div class="credit-card-head"><div><strong>${esc(c.nome)}</strong><small style="display:block;color:var(--muted);margin-top:4px">${esc(c.bandeira)} · ${esc(c.contaNome)}</small></div><div class="credit-card-actions"><button type="button" class="edit-card" data-id="${c.id}">Editar</button><button type="button" class="delete-card" data-id="${c.id}">Excluir</button></div></div><div class="credit-card-meta"><div><span>Limite</span><strong>${formatMoney(c.limite||0,c.moeda||"BRL")}</strong></div><div><span>Fechamento</span><strong>Dia ${c.fechamento}</strong></div><div><span>Vencimento</span><strong>Dia ${c.vencimento}</strong></div></div></article>`).join(""):'<div class="empty-state">Nenhum cartão cadastrado.</div>';}
function reset(){editing=null;form.reset();title.textContent="Novo cartão";save.textContent="Salvar cartão";cancel.classList.add("hidden");account.value="";currency.innerHTML="";currencyMirror.innerHTML="";resetMoneyField(limitInput,"BRL");message.textContent="";}
async function edit(id){const c=cards.find(x=>x.id===id);if(!c)return;editing=c;title.textContent="Editar cartão";save.textContent="Salvar alterações";cancel.classList.remove("hidden");$("cardNome").value=c.nome||"";account.value=c.contaId;await refreshCurrencies(c.moeda||"BRL");$("cardBandeira").value=c.bandeira||"Visa";$("cardFechamento").value=c.fechamento||1;$("cardVencimento").value=c.vencimento||1;setMoneyValue(limitInput,Number(c.limite||0));}
account.addEventListener("change",()=>refreshCurrencies());currency.addEventListener("change",()=>{currencyMirror.innerHTML=`<option value="${currency.value}">${currency.value}</option>`;});cancel.addEventListener("click",reset);
list.addEventListener("click",async e=>{const eb=e.target.closest(".edit-card"),db=e.target.closest(".delete-card");if(eb)return edit(eb.dataset.id);if(!db||!confirm("Excluir este cartão?"))return;await deleteDoc(doc(db,"users",user.uid,"cartoes",db.dataset.id));if(editing?.id===db.dataset.id)reset();});
form.addEventListener("submit",async e=>{e.preventDefault();const acc=accounts.find(a=>a.id===account.value),nome=$("cardNome").value.trim(),bandeira=$("cardBandeira").value,moeda=currency.value,limite=getMoneyValue(limitInput),fechamento=Number($("cardFechamento").value),vencimento=Number($("cardVencimento").value);if(!acc||!nome||!moeda||!fechamento||!vencimento){message.textContent="Preencha todos os campos obrigatórios.";message.className="message error";return;}const record={nome,contaId:acc.id,contaNome:acc.nome,bandeira,moeda,limite:Number(limite||0),fechamento,vencimento,atualizadoEm:serverTimestamp()};try{if(editing)await updateDoc(doc(db,"users",user.uid,"cartoes",editing.id),record);else await addDoc(collection(db,"users",user.uid,"cartoes"),{...record,criadoEm:serverTimestamp()});reset();message.textContent=editing?"Cartão atualizado.":"Cartão cadastrado.";message.className="message success";}catch(err){console.error(err);message.textContent="Não foi possível salvar o cartão.";message.className="message error";}});
onAuthStateChanged(auth,async current=>{user=current;if(stop)stop();cards=[];render();if(!current)return;const snap=await getDocs(collection(db,"users",current.uid,"contas"));accounts=snap.docs.map(d=>({id:d.id,...d.data()}));renderAccounts();reset();stop=onSnapshot(query(collection(db,"users",current.uid,"cartoes"),orderBy("criadoEm","desc")),s=>{cards=s.docs.map(d=>({id:d.id,...d.data()}));render();});});