import { auth, db } from "./firebase.js";
import { formatMoney, getMoneyCurrency, getMoneyValue, resetMoneyField } from "./money.js";
import { getBank } from "./bank-picker.js";
import { convertAccountsToBRL } from "./exchange.js";
import { addDoc, collection, deleteDoc, doc, onSnapshot, orderBy, query, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";

const form=document.getElementById("contaForm"), bancoInput=document.getElementById("contaBanco"), nomeLivreGrupo=document.getElementById("contaNomeLivreGrupo"), nomeLivreInput=document.getElementById("contaNomeLivre"), tipoInput=document.getElementById("contaTipo"), saldoInput=document.getElementById("contaSaldoInicial"), lista=document.getElementById("listaContas"), mensagem=document.getElementById("contaMensagem"), saldoTotal=document.getElementById("saldoTotal"), exchangeStatus=document.getElementById("exchangeStatus");
let usuarioAtual=null, pararEscuta=null;
function mostrarMensagem(texto="",tipo=""){mensagem.textContent=texto;mensagem.className=`message ${tipo}`.trim()}
function escapeHtml(valor=""){return String(valor).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c])}
function obterDadosInstituicao(){const chave=bancoInput.value;if(chave==="outro"){const nome=nomeLivreInput.value.trim();return{chave:"outro",nome,simbolo:nome?nome.slice(0,3).toUpperCase():"OUT",cor:"#607d8b",segmento:"Livre",logo:""}}const banco=getBank(chave);return banco?{chave:banco.id,...banco}:null}
function logoMarkup(c){if(!c.logo)return `<span class="bank-symbol" style="--bank-color:${escapeHtml(c.cor||"#607d8b")}">${escapeHtml(c.simbolo||"CTA")}</span>`;return `<span class="bank-symbol bank-logo" style="--bank-color:${escapeHtml(c.cor||"#607d8b")}"><img src="${escapeHtml(c.logo)}" alt="" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><span hidden>${escapeHtml(c.simbolo||"CTA")}</span></span>`}
async function atualizarSaldoConvertido(contas){if(!contas.length){saldoTotal.textContent=formatMoney(0,"BRL");exchangeStatus.textContent="Aguardando contas.";return}exchangeStatus.textContent="Atualizando cotações...";try{const result=await convertAccountsToBRL(contas);saldoTotal.textContent=formatMoney(result.total,"BRL");const indisponiveis=result.unavailable.length?` · sem cotação: ${result.unavailable.join(", ")}`:"";exchangeStatus.textContent=`Cotações de referência de ${result.latestDate||"data mais recente"}${indisponiveis}`}catch(e){const totalBRL=contas.filter(c=>(c.moeda||"BRL")==="BRL").reduce((s,c)=>s+Number(c.saldoInicial||0),0);saldoTotal.textContent=formatMoney(totalBRL,"BRL");exchangeStatus.textContent="Conversão indisponível; exibindo somente contas em BRL.";console.error(e)}}
function renderizarContas(contas){atualizarSaldoConvertido(contas);if(!contas.length){lista.innerHTML='<div class="empty-state">Nenhuma conta cadastrada.</div>';return}lista.innerHTML=contas.map(c=>{const moeda=c.moeda||"BRL";return `<article class="account-item"><div class="account-main">${logoMarkup(c)}<div><strong>${escapeHtml(c.nome)}</strong><span>${escapeHtml(c.tipo)}${c.segmento?` · ${escapeHtml(c.segmento)}`:""} · ${escapeHtml(moeda)}</span></div></div><div class="account-value"><strong>${formatMoney(c.saldoInicial,moeda)}</strong><button type="button" class="delete-account" data-id="${c.id}" aria-label="Excluir ${escapeHtml(c.nome)}">Excluir</button></div></article>`}).join("");lista.querySelectorAll(".delete-account").forEach(b=>b.addEventListener("click",async()=>{if(!usuarioAtual||!confirm("Excluir esta conta?"))return;try{await deleteDoc(doc(db,"users",usuarioAtual.uid,"contas",b.dataset.id))}catch(e){mostrarMensagem("Não foi possível excluir a conta.","error");console.error(e)}}))}
bancoInput.addEventListener("change",()=>{const livre=bancoInput.value==="outro";nomeLivreGrupo.classList.toggle("hidden",!livre);nomeLivreInput.required=livre;if(!livre)nomeLivreInput.value=""});
form.addEventListener("submit",async event=>{event.preventDefault();mostrarMensagem();if(!usuarioAtual){mostrarMensagem("Faça login para cadastrar uma conta.","error");return}const instituicao=obterDadosInstituicao(),tipo=tipoInput.value,saldoInicial=getMoneyValue(saldoInput),moeda=getMoneyCurrency(saldoInput);if(!instituicao){mostrarMensagem("Selecione um banco ou a opção de nome livre.","error");return}if(!instituicao.nome){mostrarMensagem("Informe o nome da conta.","error");return}if(!Number.isFinite(saldoInicial)){mostrarMensagem("Informe um saldo inicial válido.","error");return}try{await addDoc(collection(db,"users",usuarioAtual.uid,"contas"),{bancoId:instituicao.chave,nome:instituicao.nome,simbolo:instituicao.simbolo,cor:instituicao.cor,logo:instituicao.logo||"",segmento:instituicao.segmento,tipo,saldoInicial,moeda,ativa:true,criadoEm:serverTimestamp(),atualizadoEm:serverTimestamp()});form.reset();bancoInput.value="";document.getElementById("bankPickerTrigger").innerHTML="<span>🔎 Pesquisar banco ou instituição</span>";nomeLivreGrupo.classList.add("hidden");nomeLivreInput.required=false;resetMoneyField(saldoInput,"BRL");mostrarMensagem("Conta cadastrada com sucesso.","success")}catch(e){mostrarMensagem("Não foi possível cadastrar a conta.","error");console.error(e)}});
onAuthStateChanged(auth,user=>{usuarioAtual=user;if(pararEscuta)pararEscuta();if(!user){renderizarContas([]);return}const contasQuery=query(collection(db,"users",user.uid,"contas"),orderBy("criadoEm","desc"));pararEscuta=onSnapshot(contasQuery,snapshot=>renderizarContas(snapshot.docs.map(d=>({id:d.id,...d.data()}))),e=>{mostrarMensagem("Não foi possível carregar as contas.","error");console.error(e)})});