import { auth, db } from "./firebase.js";
import { formatMoney, getMoneyValue, resetMoneyField } from "./money.js";
import { addDoc, collection, deleteDoc, doc, getDocs, onSnapshot, orderBy, query, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";

const content=document.getElementById("content");
const view=document.createElement("div");
view.id="receitas";view.className="app-view hidden";
view.innerHTML=`<div class="page-grid revenue-layout"><article class="panel"><h3>Nova receita</h3><form id="receitaForm" class="account-form"><label for="receitaConta">Conta de destino</label><select id="receitaConta" required></select><label for="receitaTipo">Tipo de receita</label><select id="receitaTipo"></select><label for="receitaDescricao">Descrição</label><input id="receitaDescricao" maxlength="80" placeholder="Ex.: Salário de agosto" required><label for="receitaData">Data</label><input id="receitaData" type="date" required><label for="receitaValor">Valor</label><div class="money-field" data-money-field><div class="money-input-row"><select id="receitaMoeda" data-money-currency></select><input id="receitaValor" data-money-input type="text" inputmode="decimal" value="0,00"><button type="button" class="calculator-toggle" data-money-calculator>🧮</button></div></div><button class="primary form-button" type="submit">Salvar receita</button><p id="receitaMensagem" class="message"></p></form></article><article class="panel"><div class="panel-heading"><div><h3>Receitas</h3><small id="totalReceitasFiltradas"></small></div></div><div class="filter-grid"><select id="filtroReceitaConta"></select><select id="filtroReceitaTipo"></select><input id="filtroReceitaInicio" type="date" aria-label="Data inicial"><input id="filtroReceitaFim" type="date" aria-label="Data final"></div><div id="listaReceitas"><div class="empty-state">Nenhuma receita cadastrada.</div></div></article></div>`;
content.insertBefore(view,document.getElementById("placeholderView"));

const style=document.createElement("style");style.textContent=`.revenue-layout{grid-template-columns:minmax(300px,380px) minmax(0,1fr)}.filter-grid{display:grid;grid-template-columns:repeat(4,minmax(120px,1fr));gap:8px;margin-bottom:14px}.filter-grid>*{padding:10px;border:1px solid var(--border);border-radius:9px;background:white}.transaction-item{display:flex;justify-content:space-between;gap:16px;padding:14px 0;border-bottom:1px solid var(--border)}.transaction-item span{display:block;margin-top:4px;color:var(--muted);font-size:.88rem}.transaction-value{text-align:right}.transaction-value strong{color:var(--secondary)}.transaction-value button{display:block;margin:5px 0 0 auto;border:0;background:transparent;color:var(--danger)}@media(max-width:980px){.revenue-layout{grid-template-columns:1fr}.filter-grid{grid-template-columns:1fr 1fr}}@media(max-width:520px){.filter-grid{grid-template-columns:1fr}.transaction-item{align-items:flex-start}}`;document.head.appendChild(style);

const $=(id)=>document.getElementById(id);
const form=$("receitaForm"), contaSelect=$("receitaConta"), moedaSelect=$("receitaMoeda"), valorInput=$("receitaValor"), mensagem=$("receitaMensagem"), lista=$("listaReceitas");
const filtroConta=$("filtroReceitaConta"), filtroInicio=$("filtroReceitaInicio"), filtroFim=$("filtroReceitaFim"), filtroTipo=$("filtroReceitaTipo"), total=$("totalReceitasFiltradas");
let usuario=null, pararReceitas=null, contas=[], receitas=[];
const tipos=["Salário","Freelance","Vendas","Rendimentos","Aluguel recebido","Reembolso","Presente","Outros"];
function esc(v=""){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]);}
function msg(texto="",tipo=""){mensagem.textContent=texto;mensagem.className=`message ${tipo}`.trim();}
function dateParts(data){const d=new Date(`${data}T12:00:00`),mes=d.getMonth()+1;return{ano:d.getFullYear(),mes,trimestre:Math.ceil(mes/3),semestre:mes<=6?1:2,dataChave:data};}
function hoje(){return new Date().toISOString().slice(0,10);}
async function moedasDaConta(conta){const extras=await getDocs(collection(db,"users",usuario.uid,"contas",conta.id,"moedas"));return [...new Set([conta.moeda||"BRL",...extras.docs.map(d=>d.data().codigo)])];}
async function atualizarMoedas(){const conta=contas.find(c=>c.id===contaSelect.value);if(!conta){moedaSelect.innerHTML="";return;}const moedas=await moedasDaConta(conta);moedaSelect.innerHTML=moedas.map(m=>`<option value="${m}">${m}</option>`).join("");}
function renderFiltros(){const options=contas.map(c=>`<option value="${c.id}">${esc(c.nome)}</option>`).join("");contaSelect.innerHTML=`<option value="">Selecione...</option>${options}`;filtroConta.innerHTML=`<option value="">Todas as contas</option>${options}`;$("receitaTipo").innerHTML=tipos.map(t=>`<option>${t}</option>`).join("");filtroTipo.innerHTML=`<option value="">Todos os tipos</option>${tipos.map(t=>`<option>${t}</option>`).join("")}`;}
function filtradas(){return receitas.filter(r=>(!filtroConta.value||r.contaId===filtroConta.value)&&(!filtroTipo.value||r.tipoReceita===filtroTipo.value)&&(!filtroInicio.value||r.data>=filtroInicio.value)&&(!filtroFim.value||r.data<=filtroFim.value));}
function render(){const rows=filtradas();const soma=rows.filter(r=>(r.moeda||"BRL")==="BRL").reduce((s,r)=>s+Number(r.valor||0),0);total.textContent=`Total em BRL: ${formatMoney(soma,"BRL")}`;lista.innerHTML=rows.length?rows.map(r=>`<article class="transaction-item"><div><strong>${esc(r.descricao)}</strong><span>${esc(r.tipoReceita)} · ${esc(r.contaNome)} · ${esc(r.data)}</span></div><div class="transaction-value"><strong>+${formatMoney(r.valor,r.moeda||"BRL")}</strong><button type="button" class="delete-revenue" data-id="${r.id}" data-account="${r.contaId}" data-movement="${r.movimentacaoId||""}">Excluir</button></div></article>`).join(""):'<div class="empty-state">Nenhuma receita encontrada.</div>';}
contaSelect.addEventListener("change",atualizarMoedas);[filtroConta,filtroInicio,filtroFim,filtroTipo].forEach(el=>el.addEventListener("change",render));
lista.addEventListener("click",async e=>{const b=e.target.closest(".delete-revenue");if(!b||!confirm("Excluir esta receita?"))return;await deleteDoc(doc(db,"users",usuario.uid,"receitas",b.dataset.id));if(b.dataset.movement)await deleteDoc(doc(db,"users",usuario.uid,"contas",b.dataset.account,"movimentacoes",b.dataset.movement));});
form.addEventListener("submit",async e=>{e.preventDefault();msg();const conta=contas.find(c=>c.id===contaSelect.value),valor=getMoneyValue(valorInput),data=$("receitaData").value,descricao=$("receitaDescricao").value.trim(),tipoReceita=$("receitaTipo").value,moeda=moedaSelect.value;if(!conta)return msg("Selecione uma conta.","error");if(!descricao)return msg("Informe a descrição.","error");if(!Number.isFinite(valor)||valor<=0)return msg("Informe um valor maior que zero.","error");const periodo=dateParts(data);try{const mov=await addDoc(collection(db,"users",usuario.uid,"contas",conta.id,"movimentacoes"),{tipo:"receita",categoria:tipoReceita,descricao,valor,moeda,data,...periodo,origem:"receitas",criadoEm:serverTimestamp()});await addDoc(collection(db,"users",usuario.uid,"receitas"),{contaId:conta.id,contaNome:conta.nome,tipoReceita,descricao,valor,moeda,data,...periodo,movimentacaoId:mov.id,criadoEm:serverTimestamp()});form.reset();$("receitaData").value=hoje();resetMoneyField(valorInput,"BRL");moedaSelect.innerHTML="";msg("Receita cadastrada e adicionada ao saldo da conta.","success");}catch(err){msg("Não foi possível cadastrar a receita.","error");console.error(err);}});
onAuthStateChanged(auth,async user=>{usuario=user;if(pararReceitas)pararReceitas();if(!user)return;const snap=await getDocs(collection(db,"users",user.uid,"contas"));contas=snap.docs.map(d=>({id:d.id,...d.data()}));renderFiltros();$("receitaData").value=hoje();pararReceitas=onSnapshot(query(collection(db,"users",user.uid,"receitas"),orderBy("data","desc")),s=>{receitas=s.docs.map(d=>({id:d.id,...d.data()}));render();});});