import { auth, db } from "./firebase.js";
import { getMoneyValue } from "./money.js";
import { addDoc, arrayUnion, collection, deleteDoc, doc, getDoc, getDocs, serverTimestamp, updateDoc } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";

const COLLECTIONS={receita:"receitas",despesa:"despesas",transferencia:"transferencias"};
let currentUser=null,syncing=false;
const pad=n=>String(n).padStart(2,"0");
const monthKey=data=>String(data).slice(0,7);
function parts(data){const d=new Date(`${data}T12:00:00`),m=d.getMonth()+1;return{ano:d.getFullYear(),mes:m,trimestre:Math.ceil(m/3),semestre:m<=6?1:2,dataChave:data};}
function addMonths(data,n){const [y,m,d]=data.split("-").map(Number),base=new Date(y,m-1+n,1),last=new Date(base.getFullYear(),base.getMonth()+1,0).getDate();return `${base.getFullYear()}-${pad(base.getMonth()+1)}-${pad(Math.min(d,last))}`;}
function previousMonthEnd(data){const [y,m]=data.split("-").map(Number),d=new Date(y,m-1,0);return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;}
function monthsBetween(start,end,max=600){const out=[];for(let i=0;i<max;i++){const d=addMonths(start,i);if(d>end)break;out.push(d);}return out;}
function esc(v=""){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]);}

function injectStyles(){if(document.getElementById("recurrence-styles"))return;const s=document.createElement("style");s.id="recurrence-styles";s.textContent=`
.recurrence-box{margin-top:14px;padding:13px;border:1px solid var(--border);border-radius:11px;background:#fafcff}.recurrence-box label{margin-top:8px!important}.recurrence-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.recurrence-preview{display:block;margin-top:8px;color:var(--muted);line-height:1.35}.recurrence-hidden{display:none!important}.delete-series-modal{position:fixed;inset:0;z-index:7000;display:grid;place-items:center;padding:18px}.delete-series-backdrop{position:absolute;inset:0;background:rgba(15,23,42,.58)}.delete-series-card{position:relative;width:min(480px,100%);background:white;border-radius:16px;padding:20px;box-shadow:0 24px 70px rgba(0,0,0,.3)}.delete-series-options{display:grid;gap:9px;margin-top:14px}.delete-series-options button{padding:12px;border:1px solid var(--border);border-radius:10px;background:white;text-align:left}.delete-series-options .danger{color:var(--danger);font-weight:700}.delete-series-cancel{width:100%;margin-top:12px;padding:11px;border:0;border-radius:10px;background:#eef3fa}@media(max-width:520px){.recurrence-grid{grid-template-columns:1fr}}
`;document.head.appendChild(s);}injectStyles();

function recurrenceMarkup(prefix,installments=false){return `<div class="recurrence-box"><label for="${prefix}Recorrencia">Repetição</label><select id="${prefix}Recorrencia"><option value="unica">Única</option><option value="fixa">Fixa mensal</option>${installments?'<option value="parcelada">Parcelada</option>':''}<option value="periodo">Por um período</option></select><div id="${prefix}PeriodoBox" class="recurrence-hidden"><label for="${prefix}Fim">Repetir até</label><input id="${prefix}Fim" type="date"></div>${installments?`<div id="${prefix}ParcelasBox" class="recurrence-hidden"><div class="recurrence-grid"><div><label for="${prefix}Parcelas">Quantidade de parcelas</label><input id="${prefix}Parcelas" type="number" min="2" max="240" value="2"></div><div><label for="${prefix}ValorModo">Valor informado</label><select id="${prefix}ValorModo"><option value="total">Valor total</option><option value="parcela">Valor da parcela</option></select></div></div><small id="${prefix}ParcelaPreview" class="recurrence-preview"></small></div>`:""}<small id="${prefix}RecorrenciaHint" class="recurrence-preview">Lançamento único. Ele ficará previsto até ser efetivado.</small></div>`;}
function setupBox(prefix,{installments=false,valueId}){const type=document.getElementById(`${prefix}Recorrencia`),period=document.getElementById(`${prefix}PeriodoBox`),parcel=document.getElementById(`${prefix}ParcelasBox`),hint=document.getElementById(`${prefix}RecorrenciaHint`),value=document.getElementById(valueId);if(!type)return;const preview=()=>{if(!installments||type.value!=="parcelada")return;const q=Math.max(2,Number(document.getElementById(`${prefix}Parcelas`)?.value||2)),mode=document.getElementById(`${prefix}ValorModo`)?.value||"total",v=getMoneyValue(value),el=document.getElementById(`${prefix}ParcelaPreview`);if(!v||v<=0){el.textContent="Informe o valor para calcular.";return;}const parcela=mode==="total"?v/q:v,total=mode==="total"?v:v*q;el.textContent=`${q} parcelas · parcela ${parcela.toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2})} · total ${total.toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2})}`;};const refresh=()=>{const t=type.value;period?.classList.toggle("recurrence-hidden",t!=="periodo");parcel?.classList.toggle("recurrence-hidden",t!=="parcelada");hint.textContent=t==="unica"?"Lançamento único. Ele ficará previsto até ser efetivado.":t==="fixa"?"Será previsto mensalmente sem data final, até você encerrar a série.":t==="periodo"?"Será previsto neste mês e nos seguintes até a data final.":"Cada parcela será prevista no mês correspondente e só afetará o saldo quando for efetivada.";preview();};type.addEventListener("change",refresh);document.getElementById(`${prefix}Parcelas`)?.addEventListener("input",preview);document.getElementById(`${prefix}ValorModo`)?.addEventListener("change",preview);value?.addEventListener("input",preview);refresh();}
function addFields(){[{form:"receitaForm",prefix:"receita",value:"receitaValor",installments:false},{form:"despesaForm",prefix:"despesa",value:"despesaValor",installments:true},{form:"transferForm",prefix:"transfer",value:"transferValor",installments:false}].forEach(c=>{const form=document.getElementById(c.form);if(!form||document.getElementById(`${c.prefix}Recorrencia`))return;form.querySelector('button[type="submit"]')?.insertAdjacentHTML("beforebegin",recurrenceMarkup(c.prefix,c.installments));setupBox(c.prefix,{installments:c.installments,valueId:c.value});});}addFields();

function selectedText(id){const el=document.getElementById(id);return el?.selectedOptions?.[0]?.textContent?.trim()||"";}
function baseFromForm(kind){if(kind==="receita")return{contaId:document.getElementById("receitaConta").value,contaNome:selectedText("receitaConta"),categoriaId:document.getElementById("receitaCategoria").value,categoriaNome:selectedText("receitaCategoria"),subcategoria:document.getElementById("receitaSubcategoria").value,descricao:document.getElementById("receitaDescricao").value.trim(),moeda:document.getElementById("receitaMoeda").value};if(kind==="despesa")return{contaId:document.getElementById("despesaConta").value,contaNome:selectedText("despesaConta"),categoriaId:document.getElementById("despesaCategoria").value,categoriaNome:selectedText("despesaCategoria"),subcategoria:document.getElementById("despesaSubcategoria").value,descricao:document.getElementById("despesaDescricao").value.trim(),moeda:document.getElementById("despesaMoeda").value};return{origemId:document.getElementById("transferOrigem").value,origemNome:selectedText("transferOrigem"),destinoId:document.getElementById("transferDestino").value,destinoNome:selectedText("transferDestino"),categoriaId:document.getElementById("transferCategoria").value,categoriaNome:selectedText("transferCategoria"),subcategoria:document.getElementById("transferSubcategoria").value,descricao:document.getElementById("transferDescricao").value.trim(),moeda:document.getElementById("transferMoeda").value};}
function formData(kind){const p=kind==="receita"?"receita":kind==="despesa"?"despesa":"transfer",data=document.getElementById(`${p}Data`).value,valor=getMoneyValue(document.getElementById(`${p}Valor`)),tipo=document.getElementById(`${p}Recorrencia`)?.value||"unica",out={data,valor,tipo,base:baseFromForm(kind)};if(tipo==="periodo")out.fim=document.getElementById(`${p}Fim`).value;if(tipo==="parcelada"){out.qtd=Math.max(2,Number(document.getElementById(`${p}Parcelas`).value||2));out.valorModo=document.getElementById(`${p}ValorModo`).value;}return out;}
function validate(kind,d){if(!currentUser)return"Usuário não autenticado.";if(!d.data||!d.valor||d.valor<=0)return"Informe data e valor maior que zero.";if(!d.base.moeda||!d.base.categoriaId||!d.base.descricao)return"Preencha os campos obrigatórios.";if(kind==="transferencia"&&(!d.base.origemId||!d.base.destinoId||d.base.origemId===d.base.destinoId))return"Selecione contas diferentes.";if(kind!=="transferencia"&&!d.base.contaId)return"Selecione uma conta.";if(d.tipo==="periodo"&&(!d.fim||d.fim<d.data))return"Informe uma data final válida.";return"";}
async function createOccurrence(kind,{serieId=null,tipo="unica",base,data,valor,parcelaNumero=null,parcelasTotal=null}){await addDoc(collection(db,"users",currentUser.uid,COLLECTIONS[kind]),{...base,valor,data,...parts(data),serieId,recorrenciaTipo:tipo,competencia:monthKey(data),parcelaNumero,parcelasTotal,planejada:true,efetivada:false,criadoEm:serverTimestamp(),atualizadoEm:serverTimestamp()});}
async function createFromForm(kind,d){if(d.tipo==="unica"){await createOccurrence(kind,{base:d.base,data:d.data,valor:d.valor});return;}const valorParcela=d.tipo==="parcelada"?(d.valorModo==="total"?d.valor/d.qtd:d.valor):d.valor,valorTotal=d.tipo==="parcelada"?(d.valorModo==="total"?d.valor:d.valor*d.qtd):null,fim=d.tipo==="periodo"?d.fim:d.tipo==="parcelada"?addMonths(d.data,d.qtd-1):null;const serie={operacao:kind,tipoRecorrencia:d.tipo,inicio:d.data,fim,quantidade:d.tipo==="parcelada"?d.qtd:null,valorParcela,valorTotal,base:d.base,excecoes:[],ativo:true,criadoEm:serverTimestamp(),atualizadoEm:serverTimestamp()};const ref=await addDoc(collection(db,"users",currentUser.uid,"recorrencias"),serie);if(d.tipo==="fixa"){await createOccurrence(kind,{serieId:ref.id,tipo:d.tipo,base:d.base,data:d.data,valor:d.valor});return;}const dates=d.tipo==="parcelada"?Array.from({length:d.qtd},(_,i)=>addMonths(d.data,i)):monthsBetween(d.data,d.fim);for(let i=0;i<dates.length;i++)await createOccurrence(kind,{serieId:ref.id,tipo:d.tipo,base:d.base,data:dates[i],valor:valorParcela,parcelaNumero:d.tipo==="parcelada"?i+1:null,parcelasTotal:d.tipo==="parcelada"?d.qtd:null});}
function resetForm(kind){const p=kind==="receita"?"receita":kind==="despesa"?"despesa":"transfer",form=document.getElementById(kind==="transferencia"?"transferForm":`${p}Form`);form?.reset();const type=document.getElementById(`${p}Recorrencia`);if(type){type.value="unica";type.dispatchEvent(new Event("change"));}}
function intercept(kind,formId){const form=document.getElementById(formId);if(!form)return;form.addEventListener("submit",async e=>{const title=document.getElementById(kind==="receita"?"receitaFormTitulo":kind==="despesa"?"despesaFormTitulo":"transferFormTitle")?.textContent||"";if(/^Editar/i.test(title))return;e.preventDefault();e.stopImmediatePropagation();const d=formData(kind),err=validate(kind,d),message=document.getElementById(kind==="receita"?"receitaMensagem":kind==="despesa"?"despesaMensagem":"transferMensagem");if(err){if(message){message.textContent=err;message.className="message error";}return;}try{await createFromForm(kind,d);if(message){message.textContent="Operação prevista criada. Use Efetivar quando ela realmente acontecer.";message.className="message success";}resetForm(kind);}catch(error){console.error(error);if(message){message.textContent="Não foi possível salvar a operação.";message.className="message error";}}},true);}intercept("receita","receitaForm");intercept("despesa","despesaForm");intercept("transferencia","transferForm");

async function syncRecurrences(targetStart=null){if(!currentUser||syncing)return;syncing=true;try{const [seriesSnap,rSnap,dSnap,tSnap]=await Promise.all([getDocs(collection(db,"users",currentUser.uid,"recorrencias")),getDocs(collection(db,"users",currentUser.uid,"receitas")),getDocs(collection(db,"users",currentUser.uid,"despesas")),getDocs(collection(db,"users",currentUser.uid,"transferencias"))]);const existing={receita:rSnap.docs.map(d=>d.data()),despesa:dSnap.docs.map(d=>d.data()),transferencia:tSnap.docs.map(d=>d.data())};for(const sdoc of seriesSnap.docs){const s={id:sdoc.id,...sdoc.data()};if(!s.ativo||s.tipoRecorrencia!=="fixa")continue;const dates=targetStart?[targetStart]:[new Date().toISOString().slice(0,10)];for(const target of dates){const idx=(Number(target.slice(0,4))-Number(s.inicio.slice(0,4)))*12+Number(target.slice(5,7))-Number(s.inicio.slice(5,7));if(idx<0)continue;const date=addMonths(s.inicio,idx),key=monthKey(date);if(s.fim&&date>s.fim||new Set(s.excecoes||[]).has(key))continue;if((existing[s.operacao]||[]).some(r=>r.serieId===s.id&&r.competencia===key))continue;await createOccurrence(s.operacao,{serieId:s.id,tipo:"fixa",base:s.base,data:date,valor:Number(s.valorParcela||0)});}}}catch(error){console.error("Falha ao sincronizar recorrências:",error);}finally{syncing=false;}}

function deleteModal(record){return new Promise(resolve=>{document.getElementById("deleteSeriesModal")?.remove();const month=new Date(`${record.data}T12:00:00`).toLocaleDateString("pt-BR",{month:"long",year:"numeric"}),modal=document.createElement("div");modal.id="deleteSeriesModal";modal.className="delete-series-modal";modal.innerHTML=`<div class="delete-series-backdrop"></div><section class="delete-series-card"><h3>Excluir operação recorrente</h3><p>O que deseja apagar a partir de <strong>${esc(month)}</strong>?</p><div class="delete-series-options"><button data-scope="one">Apagar só esta (${esc(month)})</button><button data-scope="all" class="danger">Apagar desde o início</button><button data-scope="future" class="danger">Apagar deste mês em diante</button></div><button class="delete-series-cancel" data-scope="cancel">Cancelar</button></section>`;document.body.appendChild(modal);const done=v=>{modal.remove();resolve(v);};modal.addEventListener("click",e=>{const b=e.target.closest("[data-scope]");if(b)done(b.dataset.scope);else if(e.target.classList.contains("delete-series-backdrop"))done("cancel");});});}
async function removeMovements(kind,r){if(kind==="receita"||kind==="despesa"){if(r.movimentacaoId)await deleteDoc(doc(db,"users",currentUser.uid,"contas",r.contaId,"movimentacoes",r.movimentacaoId));return;}if(r.movSaida)await deleteDoc(doc(db,"users",currentUser.uid,"contas",r.origemId,"movimentacoes",r.movSaida));if(r.movEntrada)await deleteDoc(doc(db,"users",currentUser.uid,"contas",r.destinoId,"movimentacoes",r.movEntrada));}
async function deleteRoot(kind,r){await removeMovements(kind,r);await deleteDoc(doc(db,"users",currentUser.uid,COLLECTIONS[kind],r.id));}
async function deleteScope(kind,record,scope){const serieRef=doc(db,"users",currentUser.uid,"recorrencias",record.serieId),snap=await getDocs(collection(db,"users",currentUser.uid,COLLECTIONS[kind])),rows=snap.docs.map(d=>({id:d.id,...d.data()})).filter(r=>r.serieId===record.serieId);if(scope==="one"){await deleteRoot(kind,record);await updateDoc(serieRef,{excecoes:arrayUnion(record.competencia||monthKey(record.data)),atualizadoEm:serverTimestamp()});return;}if(scope==="all"){for(const r of rows)await deleteRoot(kind,r);await deleteDoc(serieRef);return;}for(const r of rows.filter(r=>monthKey(r.data)>=monthKey(record.data)))await deleteRoot(kind,r);await updateDoc(serieRef,{fim:previousMonthEnd(record.data),ativo:false,atualizadoEm:serverTimestamp()});}
const deleteMap=[{selector:".delete-revenue",kind:"receita"},{selector:".delete-expense",kind:"despesa"},{selector:".delete-transfer",kind:"transferencia"}];
document.addEventListener("click",async e=>{for(const item of deleteMap){const btn=e.target.closest(item.selector);if(!btn||!currentUser)continue;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const snap=await getDoc(doc(db,"users",currentUser.uid,COLLECTIONS[item.kind],btn.dataset.id));if(!snap.exists())return;const record={id:snap.id,...snap.data()};if(!record.serieId){if(!confirm("Tem certeza que deseja apagar esta operação? Esta ação não pode ser desfeita."))return;try{await deleteRoot(item.kind,record);}catch(error){console.error(error);alert("Não foi possível apagar a operação.");}return;}const scope=await deleteModal(record);if(!scope||scope==="cancel")return;const labels={one:"somente esta ocorrência",all:"toda a série desde o início",future:"esta ocorrência e todas as seguintes"};if(!confirm(`Tem certeza que deseja apagar ${labels[scope]}? Esta ação não pode ser desfeita.`))return;try{await deleteScope(item.kind,record,scope);}catch(error){console.error(error);alert("Não foi possível concluir a exclusão.");}return;}},true);

onAuthStateChanged(auth,user=>{currentUser=user;if(user)setTimeout(()=>syncRecurrences(),80);});
window.addEventListener("period-change",e=>{if(!currentUser)return;const d=e.detail||{};if(!["dashboard","receitas","despesas","transferencias"].includes(d.viewId))return;setTimeout(()=>syncRecurrences(d.start||null),30);});
export { syncRecurrences };
