import { auth, db } from "./firebase.js";
import { getMoneyValue } from "./money.js";
import { addDoc, arrayUnion, collection, deleteDoc, doc, getDoc, getDocs, serverTimestamp, updateDoc } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";

const COLLECTIONS={receita:"receitas",despesa:"despesas",transferencia:"transferencias"};
let currentUser=null,syncing=false;
const pad=n=>String(n).padStart(2,"0"), monthKey=d=>String(d).slice(0,7);
function parts(data){const d=new Date(`${data}T12:00:00`),m=d.getMonth()+1;return{ano:d.getFullYear(),mes:m,trimestre:Math.ceil(m/3),semestre:m<=6?1:2,dataChave:data};}
function addMonths(data,n){const [y,m,d]=data.split("-").map(Number),base=new Date(y,m-1+n,1),last=new Date(base.getFullYear(),base.getMonth()+1,0).getDate();return `${base.getFullYear()}-${pad(base.getMonth()+1)}-${pad(Math.min(d,last))}`;}
function previousMonthEnd(data){const [y,m]=data.split("-").map(Number),d=new Date(y,m-1,0);return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;}
function monthsBetween(start,end){const out=[];for(let i=0;i<600;i++){const d=addMonths(start,i);if(d>end)break;out.push(d);}return out;}
function splitTotal(total,q){const cents=Math.round(Number(total)*100),base=Math.floor(cents/q),rest=cents-base*q;return Array.from({length:q},(_,i)=>(base+(i<rest?1:0))/100);}
const esc=(v="")=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]);

function injectStyles(){if(document.getElementById("recurrence-styles"))return;const s=document.createElement("style");s.id="recurrence-styles";s.textContent=`.recurrence-box{margin-top:14px;padding:13px;border:1px solid var(--border);border-radius:11px;background:#fafcff}.recurrence-box label{margin-top:8px!important}.recurrence-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.recurrence-preview{display:block;margin-top:8px;color:var(--muted);line-height:1.35}.recurrence-hidden{display:none!important}.delete-series-modal{position:fixed;inset:0;z-index:7000;display:grid;place-items:center;padding:18px}.delete-series-backdrop{position:absolute;inset:0;background:rgba(15,23,42,.58)}.delete-series-card{position:relative;width:min(480px,100%);background:white;border-radius:16px;padding:20px;box-shadow:0 24px 70px rgba(0,0,0,.3)}.delete-series-options{display:grid;gap:9px;margin-top:14px}.delete-series-options button{padding:12px;border:1px solid var(--border);border-radius:10px;background:white;text-align:left}.delete-series-options .danger{color:var(--danger);font-weight:700}.delete-series-cancel{width:100%;margin-top:12px;padding:11px;border:0;border-radius:10px;background:#eef3fa}@media(max-width:520px){.recurrence-grid{grid-template-columns:1fr}}`;document.head.appendChild(s);}injectStyles();
function markup(prefix,installments){return `<div class="recurrence-box"><label for="${prefix}Recorrencia">Repetição</label><select id="${prefix}Recorrencia"><option value="unica">Única</option><option value="fixa">Fixa mensal</option>${installments?'<option value="parcelada">Parcelada</option>':''}<option value="periodo">Por um período</option></select><div id="${prefix}PeriodoBox" class="recurrence-hidden"><label for="${prefix}Fim">Repetir até</label><input id="${prefix}Fim" type="date"></div>${installments?`<div id="${prefix}ParcelasBox" class="recurrence-hidden"><div class="recurrence-grid"><div><label>Quantidade de parcelas</label><input id="${prefix}Parcelas" type="number" min="2" max="240" value="2"></div><div><label>Valor informado</label><select id="${prefix}ValorModo"><option value="total">Valor total</option><option value="parcela">Valor da parcela</option></select></div></div><small id="${prefix}ParcelaPreview" class="recurrence-preview"></small></div>`:""}<small id="${prefix}RecorrenciaHint" class="recurrence-preview"></small></div>`;}
function setup(prefix,installments,valueId){const type=document.getElementById(`${prefix}Recorrencia`),value=document.getElementById(valueId);if(!type)return;const refresh=()=>{const t=type.value;document.getElementById(`${prefix}PeriodoBox`)?.classList.toggle("recurrence-hidden",t!=="periodo");document.getElementById(`${prefix}ParcelasBox`)?.classList.toggle("recurrence-hidden",t!=="parcelada");const h=document.getElementById(`${prefix}RecorrenciaHint`);if(h)h.textContent=t==="unica"?"Lançamento único. Ficará previsto até ser efetivado.":t==="fixa"?"Previsto mensalmente sem data final, até encerrar a série.":t==="periodo"?"Previsto do mês inicial até a data final.":"Cada parcela fica prevista na competência correspondente.";if(installments&&t==="parcelada"){const q=Math.max(2,Number(document.getElementById(`${prefix}Parcelas`)?.value||2)),mode=document.getElementById(`${prefix}ValorModo`)?.value||"total",v=getMoneyValue(value),el=document.getElementById(`${prefix}ParcelaPreview`);if(el){if(!v||v<=0)el.textContent="Informe o valor para calcular.";else{const vals=mode==="total"?splitTotal(v,q):Array(q).fill(Math.round(v*100)/100),total=vals.reduce((a,b)=>a+b,0);el.textContent=`${q} parcelas · primeira ${vals[0].toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2})} · total ${total.toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2})}`;}}}};type.addEventListener("change",refresh);document.getElementById(`${prefix}Parcelas`)?.addEventListener("input",refresh);document.getElementById(`${prefix}ValorModo`)?.addEventListener("change",refresh);value?.addEventListener("input",refresh);refresh();}
function addFields(){[{form:"receitaForm",p:"receita",v:"receitaValor",i:false},{form:"despesaForm",p:"despesa",v:"despesaValor",i:true},{form:"transferForm",p:"transfer",v:"transferValor",i:false}].forEach(c=>{const form=document.getElementById(c.form);if(!form||document.getElementById(`${c.p}Recorrencia`))return;form.querySelector('button[type="submit"]')?.insertAdjacentHTML("beforebegin",markup(c.p,c.i));setup(c.p,c.i,c.v);});}addFields();

const selectedText=id=>document.getElementById(id)?.selectedOptions?.[0]?.textContent?.trim()||"";
function formData(kind){const p=kind==="receita"?"receita":kind==="despesa"?"despesa":"transfer",data=document.getElementById(`${p}Data`)?.value||"",valor=getMoneyValue(document.getElementById(`${p}Valor`)),tipo=document.getElementById(`${p}Recorrencia`)?.value||"unica";let base;if(kind==="receita"||kind==="despesa")base={contaId:document.getElementById(`${p}Conta`)?.value,contaNome:selectedText(`${p}Conta`),categoriaId:document.getElementById(`${p}Categoria`)?.value,categoriaNome:selectedText(`${p}Categoria`),subcategoria:document.getElementById(`${p}Subcategoria`)?.value||"",descricao:document.getElementById(`${p}Descricao`)?.value.trim(),moeda:document.getElementById(`${p}Moeda`)?.value};else base={origemId:document.getElementById("transferOrigem")?.value,origemNome:selectedText("transferOrigem"),destinoId:document.getElementById("transferDestino")?.value,destinoNome:selectedText("transferDestino"),categoriaId:document.getElementById("transferCategoria")?.value,categoriaNome:selectedText("transferCategoria"),subcategoria:document.getElementById("transferSubcategoria")?.value||"",descricao:document.getElementById("transferDescricao")?.value.trim(),moeda:document.getElementById("transferMoeda")?.value};return{p,data,valor,tipo,base,fim:document.getElementById(`${p}Fim`)?.value||"",qtd:Math.max(2,Number(document.getElementById(`${p}Parcelas`)?.value||2)),modo:document.getElementById(`${p}ValorModo`)?.value||"total"};}
function validate(kind,d){if(!currentUser)return"Usuário não autenticado.";if(!d.data||!d.valor||d.valor<=0||!d.base.moeda||!d.base.categoriaId||!d.base.descricao)return"Preencha todos os campos obrigatórios.";if(kind==="transferencia"&&(!d.base.origemId||!d.base.destinoId||d.base.origemId===d.base.destinoId))return"Selecione contas diferentes.";if(kind!=="transferencia"&&!d.base.contaId)return"Selecione uma conta.";if(d.tipo==="periodo"&&(!d.fim||d.fim<d.data))return"Informe uma data final válida.";return"";}
async function occurrence(kind,{base,data,valor,serieId=null,tipo="unica",parcelaNumero=null,parcelasTotal=null}){await addDoc(collection(db,"users",currentUser.uid,COLLECTIONS[kind]),{...base,valor:Number(valor.toFixed(2)),data,...parts(data),serieId,recorrenciaTipo:tipo,competencia:monthKey(data),parcelaNumero,parcelasTotal,planejada:true,efetivada:false,criadoEm:serverTimestamp(),atualizadoEm:serverTimestamp()});}
async function create(kind,d){if(d.tipo==="unica")return occurrence(kind,{base:d.base,data:d.data,valor:d.valor});let fim=d.tipo==="periodo"?d.fim:d.tipo==="parcelada"?addMonths(d.data,d.qtd-1):null,values=d.tipo==="parcelada"?(d.modo==="total"?splitTotal(d.valor,d.qtd):Array(d.qtd).fill(Math.round(d.valor*100)/100)):null;const serie=await addDoc(collection(db,"users",currentUser.uid,"recorrencias"),{operacao:kind,tipoRecorrencia:d.tipo,inicio:d.data,fim,quantidade:d.tipo==="parcelada"?d.qtd:null,valorParcela:d.tipo==="parcelada"?values[0]:d.valor,valorTotal:d.tipo==="parcelada"?Number(values.reduce((a,b)=>a+b,0).toFixed(2)):null,base:d.base,excecoes:[],ativo:true,criadoEm:serverTimestamp(),atualizadoEm:serverTimestamp()});if(d.tipo==="fixa")return occurrence(kind,{base:d.base,data:d.data,valor:d.valor,serieId:serie.id,tipo:d.tipo});const dates=d.tipo==="parcelada"?Array.from({length:d.qtd},(_,i)=>addMonths(d.data,i)):monthsBetween(d.data,d.fim);for(let i=0;i<dates.length;i++)await occurrence(kind,{base:d.base,data:dates[i],valor:d.tipo==="parcelada"?values[i]:d.valor,serieId:serie.id,tipo:d.tipo,parcelaNumero:d.tipo==="parcelada"?i+1:null,parcelasTotal:d.tipo==="parcelada"?d.qtd:null});}
function reset(kind){const p=kind==="transferencia"?"transfer":kind,form=document.getElementById(kind==="transferencia"?"transferForm":`${p}Form`);form?.reset();const type=document.getElementById(`${p}Recorrencia`);if(type){type.value="unica";type.dispatchEvent(new Event("change"));}}
for(const [kind,formId,titleId,msgId] of [["receita","receitaForm","receitaFormTitulo","receitaMensagem"],["despesa","despesaForm","despesaFormTitulo","despesaMensagem"],["transferencia","transferForm","transferFormTitle","transferMensagem"]]){document.getElementById(formId)?.addEventListener("submit",async e=>{if(/^Editar/i.test(document.getElementById(titleId)?.textContent||""))return;if(e.currentTarget.querySelector(`[data-quick-settle="${kind}"]`)?.checked)return;e.preventDefault();e.stopImmediatePropagation();const d=formData(kind),err=validate(kind,d),m=document.getElementById(msgId);if(err){if(m){m.textContent=err;m.className="message error";}return;}try{await create(kind,d);if(m){m.textContent="Operação prevista criada. Use Efetivar quando ela realmente acontecer.";m.className="message success";}reset(kind);}catch(error){console.error(error);if(m){m.textContent="Não foi possível salvar a operação.";m.className="message error";}}},true);}

async function syncRecurrences(targetStart=null){if(!currentUser||syncing)return;syncing=true;try{const [seriesSnap,rSnap,dSnap,tSnap]=await Promise.all([getDocs(collection(db,"users",currentUser.uid,"recorrencias")),getDocs(collection(db,"users",currentUser.uid,"receitas")),getDocs(collection(db,"users",currentUser.uid,"despesas")),getDocs(collection(db,"users",currentUser.uid,"transferencias"))]),existing={receita:rSnap.docs.map(d=>d.data()),despesa:dSnap.docs.map(d=>d.data()),transferencia:tSnap.docs.map(d=>d.data())};for(const sd of seriesSnap.docs){const s={id:sd.id,...sd.data()};if(!s.ativo||s.tipoRecorrencia!=="fixa")continue;const target=targetStart||new Date().toISOString().slice(0,10),idx=(Number(target.slice(0,4))-Number(s.inicio.slice(0,4)))*12+Number(target.slice(5,7))-Number(s.inicio.slice(5,7));if(idx<0)continue;const date=addMonths(s.inicio,idx),key=monthKey(date);if((s.fim&&date>s.fim)||new Set(s.excecoes||[]).has(key)||(existing[s.operacao]||[]).some(r=>r.serieId===s.id&&r.competencia===key))continue;await occurrence(s.operacao,{base:s.base,data:date,valor:Number(s.valorParcela||0),serieId:s.id,tipo:"fixa"});}}catch(e){console.error("Falha ao sincronizar recorrências:",e);}finally{syncing=false;}}
function deleteModal(record){return new Promise(resolve=>{document.getElementById("deleteSeriesModal")?.remove();const modal=document.createElement("div");modal.id="deleteSeriesModal";modal.className="delete-series-modal";modal.innerHTML=`<div class="delete-series-backdrop"></div><section class="delete-series-card"><h3>Excluir operação recorrente</h3><p>Escolha o alcance da exclusão.</p><div class="delete-series-options"><button data-scope="one">Apagar só esta ocorrência</button><button data-scope="all" class="danger">Apagar desde o início</button><button data-scope="future" class="danger">Apagar deste mês em diante</button></div><button class="delete-series-cancel" data-scope="cancel">Cancelar</button></section>`;document.body.appendChild(modal);modal.addEventListener("click",e=>{const b=e.target.closest("[data-scope]");if(b){modal.remove();resolve(b.dataset.scope);}else if(e.target.classList.contains("delete-series-backdrop")){modal.remove();resolve("cancel");}});});}
async function removeMovements(kind,r){if(kind==="receita"||kind==="despesa"){if(r.movimentacaoId)await deleteDoc(doc(db,"users",currentUser.uid,"contas",r.contaId,"movimentacoes",r.movimentacaoId));}else{if(r.movSaida)await deleteDoc(doc(db,"users",currentUser.uid,"contas",r.origemId,"movimentacoes",r.movSaida));if(r.movEntrada)await deleteDoc(doc(db,"users",currentUser.uid,"contas",r.destinoId,"movimentacoes",r.movEntrada));}}
async function deleteRoot(kind,r){await removeMovements(kind,r);await deleteDoc(doc(db,"users",currentUser.uid,COLLECTIONS[kind],r.id));}
async function deleteScope(kind,record,scope){const serieRef=doc(db,"users",currentUser.uid,"recorrencias",record.serieId),snap=await getDocs(collection(db,"users",currentUser.uid,COLLECTIONS[kind])),rows=snap.docs.map(d=>({id:d.id,...d.data()})).filter(r=>r.serieId===record.serieId);if(scope==="one"){await deleteRoot(kind,record);await updateDoc(serieRef,{excecoes:arrayUnion(record.competencia||monthKey(record.data)),atualizadoEm:serverTimestamp()});return;}if(scope==="all"){for(const r of rows)await deleteRoot(kind,r);await deleteDoc(serieRef);return;}for(const r of rows.filter(r=>monthKey(r.data)>=monthKey(record.data)))await deleteRoot(kind,r);await updateDoc(serieRef,{fim:previousMonthEnd(record.data),ativo:false,atualizadoEm:serverTimestamp()});}
for(const [selector,kind] of [[".delete-revenue","receita"],[".delete-expense","despesa"],[".delete-transfer","transferencia"]])document.addEventListener("click",async e=>{const btn=e.target.closest(selector);if(!btn||!currentUser)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const snap=await getDoc(doc(db,"users",currentUser.uid,COLLECTIONS[kind],btn.dataset.id));if(!snap.exists())return;const record={id:snap.id,...snap.data()};if(!record.serieId){if(confirm("Tem certeza que deseja apagar esta operação? Esta ação não pode ser desfeita."))await deleteRoot(kind,record);return;}const scope=await deleteModal(record);if(scope==="cancel")return;const text={one:"somente esta ocorrência",all:"toda a série desde o início",future:"esta ocorrência e todas as seguintes"}[scope];if(confirm(`Tem certeza que deseja apagar ${text}? Esta ação não pode ser desfeita.`))await deleteScope(kind,record,scope);},true);

onAuthStateChanged(auth,u=>{currentUser=u;if(u)setTimeout(()=>syncRecurrences(),80);});
window.addEventListener("period-change",e=>{if(currentUser&&["dashboard","receitas","despesas","transferencias"].includes(e.detail?.viewId))setTimeout(()=>syncRecurrences(e.detail?.start||null),30);});
export {syncRecurrences};
