import { auth, db } from "./firebase.js";
import { getMoneyValue } from "./money.js";
import {
  addDoc, arrayUnion, collection, deleteDoc, doc, getDoc, getDocs,
  serverTimestamp, updateDoc
} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";

const COLLECTIONS={receita:"receitas",despesa:"despesas",transferencia:"transferencias"};
let currentUser=null;
let syncing=false;
const today=()=>new Date().toISOString().slice(0,10);
const pad=n=>String(n).padStart(2,"0");
function parts(data){const d=new Date(`${data}T12:00:00`),m=d.getMonth()+1;return{ano:d.getFullYear(),mes:m,trimestre:Math.ceil(m/3),semestre:m<=6?1:2,dataChave:data};}
function monthKey(data){return String(data).slice(0,7);}
function addMonths(data,n){const [y,m,d]=data.split("-").map(Number),base=new Date(y,m-1+n,1),last=new Date(base.getFullYear(),base.getMonth()+1,0).getDate();return `${base.getFullYear()}-${pad(base.getMonth()+1)}-${pad(Math.min(d,last))}`;}
function previousMonthEnd(data){const [y,m]=data.split("-").map(Number),d=new Date(y,m-1,0);return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;}
function monthsBetween(start,end,max=600){const out=[];for(let i=0;i<max;i++){const d=addMonths(start,i);if(d>end)break;out.push(d);}return out;}
function esc(v=""){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]);}

function injectStyles(){if(document.getElementById("recurrence-styles"))return;const s=document.createElement("style");s.id="recurrence-styles";s.textContent=`
.recurrence-box{margin-top:14px;padding:13px;border:1px solid var(--border);border-radius:11px;background:#fafcff}.recurrence-box label{margin-top:8px!important}.recurrence-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.recurrence-preview{display:block;margin-top:8px;color:var(--muted);line-height:1.35}.recurrence-hidden{display:none!important}
.series-badge{display:inline-block;margin-left:6px;padding:2px 6px;border-radius:999px;background:#eef3fa;color:var(--primary);font-size:.72rem;font-weight:700}
.delete-series-modal{position:fixed;inset:0;z-index:5000;display:grid;place-items:center;padding:18px}.delete-series-backdrop{position:absolute;inset:0;background:rgba(15,23,42,.58)}.delete-series-card{position:relative;width:min(480px,100%);background:white;border-radius:16px;padding:20px;box-shadow:0 24px 70px rgba(0,0,0,.3)}.delete-series-card h3{margin:0 0 8px}.delete-series-card p{color:var(--muted);line-height:1.45}.delete-series-options{display:grid;gap:9px;margin-top:14px}.delete-series-options button{padding:12px;border:1px solid var(--border);border-radius:10px;background:white;text-align:left}.delete-series-options button:hover{background:#eef4fb}.delete-series-options .danger{color:var(--danger);font-weight:700}.delete-series-cancel{width:100%;margin-top:12px;padding:11px;border:0;border-radius:10px;background:#eef3fa}
@media(max-width:520px){.recurrence-grid{grid-template-columns:1fr}}
`;document.head.appendChild(s);}
injectStyles();

function recurrenceMarkup(prefix,installments=false){return `<div class="recurrence-box" data-recurrence-box="${prefix}">
<label for="${prefix}Recorrencia">Repetição</label>
<select id="${prefix}Recorrencia"><option value="unica">Única</option><option value="fixa">Fixa mensal</option>${installments?'<option value="parcelada">Parcelada</option>':''}<option value="periodo">Por um período</option></select>
<div id="${prefix}PeriodoBox" class="recurrence-hidden"><label for="${prefix}Fim">Repetir até</label><input id="${prefix}Fim" type="date"></div>
${installments?`<div id="${prefix}ParcelasBox" class="recurrence-hidden"><div class="recurrence-grid"><div><label for="${prefix}Parcelas">Quantidade de parcelas</label><input id="${prefix}Parcelas" type="number" min="2" max="240" value="2"></div><div><label for="${prefix}ValorModo">Valor informado</label><select id="${prefix}ValorModo"><option value="total">Valor total</option><option value="parcela">Valor da parcela</option></select></div></div><small id="${prefix}ParcelaPreview" class="recurrence-preview"></small></div>`:""}
<small id="${prefix}RecorrenciaHint" class="recurrence-preview">Lançamento único, sem repetição.</small>
</div>`;}

function setupBox(prefix,{installments=false,valueId}){
  const type=document.getElementById(`${prefix}Recorrencia`),period=document.getElementById(`${prefix}PeriodoBox`),parcel=document.getElementById(`${prefix}ParcelasBox`),hint=document.getElementById(`${prefix}RecorrenciaHint`),value=document.getElementById(valueId);
  if(!type)return;
  const refreshInstallment=()=>{if(!installments||type.value!=="parcelada")return;const qtd=Math.max(2,Number(document.getElementById(`${prefix}Parcelas`)?.value||2)),mode=document.getElementById(`${prefix}ValorModo`)?.value||"total",v=getMoneyValue(value);const preview=document.getElementById(`${prefix}ParcelaPreview`);if(!Number.isFinite(v)||v<=0){preview.textContent="Informe o valor para calcular o parcelamento.";return;}const parcela=mode==="total"?v/qtd:v,total=mode==="total"?v:v*qtd;preview.textContent=`${qtd} parcelas · valor da parcela: ${parcela.toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2})} · valor total: ${total.toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2})}`;};
  const refresh=()=>{const t=type.value;period?.classList.toggle("recurrence-hidden",t!=="periodo");parcel?.classList.toggle("recurrence-hidden",t!=="parcelada");hint.textContent=t==="unica"?"Lançamento único, sem repetição.":t==="fixa"?"Será previsto mensalmente, sem data final, até você encerrar a série.":t==="periodo"?"Será previsto neste mês e nos meses seguintes até a data final.":"Cada parcela será prevista no mês correspondente.";refreshInstallment();};
  type.addEventListener("change",refresh);document.getElementById(`${prefix}Parcelas`)?.addEventListener("input",refreshInstallment);document.getElementById(`${prefix}ValorModo`)?.addEventListener("change",refreshInstallment);value?.addEventListener("input",refreshInstallment);refresh();
}

function addRecurrenceFields(){
  const configs=[{form:"receitaForm",prefix:"receita",value:"receitaValor",installments:false},{form:"despesaForm",prefix:"despesa",value:"despesaValor",installments:true},{form:"transferForm",prefix:"transfer",value:"transferValor",installments:false}];
  configs.forEach(c=>{const form=document.getElementById(c.form);if(!form||document.getElementById(`${c.prefix}Recorrencia`))return;const save=form.querySelector('button[type="submit"]');save.insertAdjacentHTML("beforebegin",recurrenceMarkup(c.prefix,c.installments));setupBox(c.prefix,{installments:c.installments,valueId:c.value});});
}
addRecurrenceFields();

function selectedText(id){const el=document.getElementById(id);return el?.selectedOptions?.[0]?.textContent?.trim()||"";}
function baseFromForm(kind){if(kind==="receita")return{contaId:document.getElementById("receitaConta").value,contaNome:selectedText("receitaConta"),categoriaId:document.getElementById("receitaCategoria").value,categoriaNome:selectedText("receitaCategoria"),subcategoria:document.getElementById("receitaSubcategoria").value,descricao:document.getElementById("receitaDescricao").value.trim(),moeda:document.getElementById("receitaMoeda").value};if(kind==="despesa")return{contaId:document.getElementById("despesaConta").value,contaNome:selectedText("despesaConta"),categoriaId:document.getElementById("despesaCategoria").value,categoriaNome:selectedText("despesaCategoria"),subcategoria:document.getElementById("despesaSubcategoria").value,descricao:document.getElementById("despesaDescricao").value.trim(),moeda:document.getElementById("despesaMoeda").value};return{origemId:document.getElementById("transferOrigem").value,origemNome:selectedText("transferOrigem"),destinoId:document.getElementById("transferDestino").value,destinoNome:selectedText("transferDestino"),categoriaId:document.getElementById("transferCategoria").value,categoriaNome:selectedText("transferCategoria"),subcategoria:document.getElementById("transferSubcategoria").value,descricao:document.getElementById("transferDescricao").value.trim(),moeda:document.getElementById("transferMoeda").value};}
function formData(kind){const p=kind==="receita"?"receita":kind==="despesa"?"despesa":"transfer",data=document.getElementById(`${p}Data`).value,valor=getMoneyValue(document.getElementById(`${p}Valor`)),tipo=document.getElementById(`${p}Recorrencia`).value;const out={data,valor,tipo,base:baseFromForm(kind)};if(tipo==="periodo")out.fim=document.getElementById(`${p}Fim`).value;if(tipo==="parcelada"){out.qtd=Math.max(2,Number(document.getElementById(`${p}Parcelas`).value||2));out.valorModo=document.getElementById(`${p}ValorModo`).value;}return out;}
function validateRecurring(kind,d){if(!currentUser)return"Usuário não autenticado.";if(!d.data||!d.valor||d.valor<=0)return"Preencha a data e informe um valor maior que zero.";if(!d.base.moeda||!d.base.categoriaId||!d.base.descricao)return"Preencha os campos obrigatórios.";if(kind==="transferencia"&&(!d.base.origemId||!d.base.destinoId||d.base.origemId===d.base.destinoId))return"Selecione contas de origem e destino diferentes.";if(kind!=="transferencia"&&!d.base.contaId)return"Selecione uma conta.";if(d.tipo==="periodo"&&(!d.fim||d.fim<d.data))return"Informe uma data final igual ou posterior à data inicial.";return"";}

async function createMovements(kind,base,valor,data,meta){const common={categoriaId:base.categoriaId,categoriaNome:base.categoriaNome,subcategoria:base.subcategoria||"",descricao:base.descricao,valor,moeda:base.moeda,data,...parts(data),serieId:meta.serieId,recorrenciaTipo:meta.tipo,competencia:meta.competencia||monthKey(data),parcelaNumero:meta.parcelaNumero||null,parcelasTotal:meta.parcelasTotal||null,atualizadoEm:serverTimestamp()};if(kind==="receita"||kind==="despesa"){const ref=await addDoc(collection(db,"users",currentUser.uid,"contas",base.contaId,"movimentacoes"),{...common,tipo:kind,origem:COLLECTIONS[kind],criadoEm:serverTimestamp()});return{movimentacaoId:ref.id};}const out=await addDoc(collection(db,"users",currentUser.uid,"contas",base.origemId,"movimentacoes"),{...common,tipo:"despesa",origem:"transferencias",descricao:`Transferência: ${base.descricao}`,criadoEm:serverTimestamp()});const inn=await addDoc(collection(db,"users",currentUser.uid,"contas",base.destinoId,"movimentacoes"),{...common,tipo:"receita",origem:"transferencias",descricao:`Transferência: ${base.descricao}`,criadoEm:serverTimestamp()});return{movSaida:out.id,movEntrada:inn.id};}
async function createOccurrence(kind,serieId,serie,data,valor,parcelaNumero=null,parcelasTotal=null){const collectionName=COLLECTIONS[kind],due=data<=today(),manual=kind==="receita"||kind==="despesa",meta={serieId,tipo:serie.tipoRecorrencia,parcelaNumero,parcelasTotal,competencia:monthKey(data)};const movementIds=!manual&&due?await createMovements(kind,serie.base,valor,data,meta):{};const root={...serie.base,valor,data,...parts(data),serieId,recorrenciaTipo:serie.tipoRecorrencia,competencia:monthKey(data),parcelaNumero,parcelasTotal,planejada:manual?true:!due,efetivada:manual?false:due,...movementIds,criadoEm:serverTimestamp(),atualizadoEm:serverTimestamp()};await addDoc(collection(db,"users",currentUser.uid,collectionName),root);}
async function createSeries(kind,d){const valorParcela=d.tipo==="parcelada"?(d.valorModo==="total"?d.valor/d.qtd:d.valor):d.valor,valorTotal=d.tipo==="parcelada"?(d.valorModo==="total"?d.valor:d.valor*d.qtd):null,fim=d.tipo==="periodo"?d.fim:d.tipo==="parcelada"?addMonths(d.data,d.qtd-1):null;const serie={operacao:kind,tipoRecorrencia:d.tipo,inicio:d.data,fim,quantidade:d.tipo==="parcelada"?d.qtd:null,valorParcela,valorTotal,base:d.base,excecoes:[],ativo:true,criadoEm:serverTimestamp(),atualizadoEm:serverTimestamp()};const ref=await addDoc(collection(db,"users",currentUser.uid,"recorrencias"),serie);if(d.tipo==="fixa"){await createOccurrence(kind,ref.id,serie,d.data,d.valor);return;}const dates=d.tipo==="parcelada"?Array.from({length:d.qtd},(_,i)=>addMonths(d.data,i)):monthsBetween(d.data,d.fim);for(let i=0;i<dates.length;i++)await createOccurrence(kind,ref.id,serie,dates[i],valorParcela,d.tipo==="parcelada"?i+1:null,d.tipo==="parcelada"?d.qtd:null);}
function resetRecurringForm(kind){const p=kind==="receita"?"receita":kind==="despesa"?"despesa":"transfer",form=document.getElementById(kind==="transferencia"?"transferForm":`${p}Form`);form?.reset();const type=document.getElementById(`${p}Recorrencia`);if(type){type.value="unica";type.dispatchEvent(new Event("change"));}document.getElementById(`${p}Fim`)?.removeAttribute("required");}
function interceptSubmit(kind,formId){const form=document.getElementById(formId);if(!form)return;form.addEventListener("submit",async e=>{const p=kind==="receita"?"receita":kind==="despesa"?"despesa":"transfer",type=document.getElementById(`${p}Recorrencia`)?.value||"unica";if(type==="unica")return;e.preventDefault();e.stopImmediatePropagation();const d=formData(kind),err=validateRecurring(kind,d),message=document.getElementById(kind==="receita"?"receitaMensagem":kind==="despesa"?"despesaMensagem":"transferMensagem");if(err){if(message){message.textContent=err;message.className="message error";}return;}try{await createSeries(kind,d);if(message){message.textContent=kind==="transferencia"?"Transferência recorrente criada.":"Operação prevista criada. Use Efetivar quando o valor realmente entrar ou sair da conta.";message.className="message success";}resetRecurringForm(kind);}catch(error){console.error(error);if(message){message.textContent="Não foi possível criar a recorrência.";message.className="message error";}}},true);}
interceptSubmit("receita","receitaForm");interceptSubmit("despesa","despesaForm");interceptSubmit("transferencia","transferForm");

async function activateTransfer(id,data){if(data.planejada===false||data.data>today())return;const ids=await createMovements("transferencia",data,Number(data.valor||0),data.data,{serieId:data.serieId,tipo:data.recorrenciaTipo,parcelaNumero:data.parcelaNumero,parcelasTotal:data.parcelasTotal,competencia:data.competencia});await updateDoc(doc(db,"users",currentUser.uid,"transferencias",id),{...ids,planejada:false,efetivada:true,atualizadoEm:serverTimestamp()});}
async function existingByCollection(){const result={};for(const kind of Object.keys(COLLECTIONS)){const snap=await getDocs(collection(db,"users",currentUser.uid,COLLECTIONS[kind]));result[kind]=snap.docs.map(d=>({id:d.id,...d.data()}));}return result;}
async function syncRecurrences(targetStart=null,targetEnd=null){if(!currentUser||syncing)return;syncing=true;try{const [seriesSnap,existing]=await Promise.all([getDocs(collection(db,"users",currentUser.uid,"recorrencias")),existingByCollection()]);for(const r of existing.transferencia||[])if(r.serieId&&r.planejada!==false&&r.data<=today()&&!r.movSaida)await activateTransfer(r.id,r);for(const sdoc of seriesSnap.docs){const s={id:sdoc.id,...sdoc.data()};if(!s.ativo||s.tipoRecorrencia!=="fixa")continue;const kind=s.operacao,rows=existing[kind]||[],exceptions=new Set(s.excecoes||[]),dates=monthsBetween(s.inicio,today());if(targetStart&&targetStart>today()&&!dates.some(d=>monthKey(d)===monthKey(targetStart)))dates.push(addMonths(s.inicio,Math.max(0,(Number(targetStart.slice(0,4))-Number(s.inicio.slice(0,4)))*12+Number(targetStart.slice(5,7))-Number(s.inicio.slice(5,7)))));for(const date of dates){if(date<s.inicio||(s.fim&&date>s.fim)||exceptions.has(monthKey(date)))continue;if(rows.some(r=>r.serieId===s.id&&r.competencia===monthKey(date)))continue;await createOccurrence(kind,s.id,s,date,Number(s.valorParcela||0));}}}catch(error){console.error("Falha ao sincronizar recorrências:",error);}finally{syncing=false;}}

function deleteModal(record){return new Promise(resolve=>{document.getElementById("deleteSeriesModal")?.remove();const month=new Date(`${record.data}T12:00:00`).toLocaleDateString("pt-BR",{month:"long",year:"numeric"});const modal=document.createElement("div");modal.id="deleteSeriesModal";modal.className="delete-series-modal";modal.innerHTML=`<div class="delete-series-backdrop"></div><section class="delete-series-card"><h3>Excluir operação recorrente</h3><p>Esta operação pertence a uma série. O que você deseja apagar a partir de <strong>${esc(month)}</strong>?</p><div class="delete-series-options"><button data-scope="one">Apagar somente esta ocorrência</button><button data-scope="all" class="danger">Apagar desde o início</button><button data-scope="future" class="danger">Apagar deste mês em diante</button></div><button class="delete-series-cancel" data-scope="cancel">Cancelar</button></section>`;document.body.appendChild(modal);const done=v=>{modal.remove();resolve(v);};modal.addEventListener("click",e=>{const b=e.target.closest("[data-scope]");if(b)done(b.dataset.scope);else if(e.target.classList.contains("delete-series-backdrop"))done("cancel");});});}
async function removeMovements(kind,r){if(kind==="receita"||kind==="despesa"){if(r.movimentacaoId)await deleteDoc(doc(db,"users",currentUser.uid,"contas",r.contaId,"movimentacoes",r.movimentacaoId));return;}if(r.movSaida)await deleteDoc(doc(db,"users",currentUser.uid,"contas",r.origemId,"movimentacoes",r.movSaida));if(r.movEntrada)await deleteDoc(doc(db,"users",currentUser.uid,"contas",r.destinoId,"movimentacoes",r.movEntrada));}
async function deleteRoot(kind,r){await removeMovements(kind,r);await deleteDoc(doc(db,"users",currentUser.uid,COLLECTIONS[kind],r.id));}
async function deleteSeriesScope(kind,record,scope){const serieRef=doc(db,"users",currentUser.uid,"recorrencias",record.serieId),snap=await getDocs(collection(db,"users",currentUser.uid,COLLECTIONS[kind])),rows=snap.docs.map(d=>({id:d.id,...d.data()})).filter(r=>r.serieId===record.serieId);if(scope==="one"){await deleteRoot(kind,record);await updateDoc(serieRef,{excecoes:arrayUnion(record.competencia||monthKey(record.data)),atualizadoEm:serverTimestamp()});return;}if(scope==="all"){for(const r of rows)await deleteRoot(kind,r);await deleteDoc(serieRef);return;}for(const r of rows.filter(r=>(r.competencia||monthKey(r.data))>=(record.competencia||monthKey(record.data))))await deleteRoot(kind,r);await updateDoc(serieRef,{fim:previousMonthEnd(record.data),ativo:true,atualizadoEm:serverTimestamp()});}
const deleteMap=[{selector:".delete-revenue",kind:"receita"},{selector:".delete-expense",kind:"despesa"},{selector:".delete-transfer",kind:"transferencia"}];
document.addEventListener("click",async e=>{for(const item of deleteMap){const btn=e.target.closest(item.selector);if(!btn)continue;if(!currentUser)return;const ref=doc(db,"users",currentUser.uid,COLLECTIONS[item.kind],btn.dataset.id),snap=await getDoc(ref);if(!snap.exists())return;const record={id:snap.id,...snap.data()};if(!record.serieId)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const scope=await deleteModal(record);if(!scope||scope==="cancel")return;const labels={one:"somente esta ocorrência",all:"toda a série desde o início",future:"esta ocorrência e todas as seguintes"};if(!confirm(`Tem certeza que deseja apagar ${labels[scope]}? Esta ação não pode ser desfeita.`))return;try{await deleteSeriesScope(item.kind,record,scope);}catch(error){console.error(error);alert("Não foi possível concluir a exclusão.");}return;}},true);

onAuthStateChanged(auth,user=>{currentUser=user;if(user)setTimeout(()=>syncRecurrences(),100);});
window.addEventListener("period-change",e=>{if(!currentUser)return;const view=e.detail?.viewId;if(!["dashboard","receitas","despesas","transferencias"].includes(view))return;setTimeout(()=>syncRecurrences(e.detail?.start||null,e.detail?.end||null),30);});
export { syncRecurrences };
