import { auth, db } from "./firebase.js";
import { getMoneyValue } from "./money.js";
import { addDoc, arrayUnion, collection, deleteDoc, doc, getDoc, getDocs, serverTimestamp, updateDoc } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";

const COLLECTIONS={receita:"receitas",despesa:"despesas",transferencia:"transferencias"};
const FREQUENCIES={diaria:"Diária",semanal:"Semanal",mensal:"Mensal",trimestral:"Trimestral",semestral:"Semestral",anual:"Anual"};
let currentUser=null;
let syncing=false;
const pad=n=>String(n).padStart(2,"0");
const monthKey=d=>String(d||"").slice(0,7);

function parts(data){const d=new Date(`${data}T12:00:00`),m=d.getMonth()+1;return{ano:d.getFullYear(),mes:m,trimestre:Math.ceil(m/3),semestre:m<=6?1:2,dataChave:data};}
function addDays(data,n){const d=new Date(`${data}T12:00:00`);d.setDate(d.getDate()+n);return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;}
function addMonths(data,n){const [y,m,d]=data.split("-").map(Number),base=new Date(y,m-1+n,1),last=new Date(base.getFullYear(),base.getMonth()+1,0).getDate();return `${base.getFullYear()}-${pad(base.getMonth()+1)}-${pad(Math.min(d,last))}`;}
function previousDay(data){return addDays(data,-1);}
function nextDate(start,frequency,index){if(frequency==="diaria")return addDays(start,index);if(frequency==="semanal")return addDays(start,index*7);const mult={mensal:1,trimestral:3,semestral:6,anual:12}[frequency]||1;return addMonths(start,index*mult);}
function splitTotal(total,q){const cents=Math.round(Number(total)*100),base=Math.floor(cents/q),rest=cents-base*q;return Array.from({length:q},(_,i)=>(base+(i<rest?1:0))/100);}
function datesInRange(series,start,end){const out=[];for(let i=0;i<20000;i++){const date=nextDate(series.inicio,series.frequencia||"mensal",i);if(date>end)break;if(date>=start&&(!series.fim||date<=series.fim))out.push(date);}return out;}

function addStyles(){if(document.getElementById("recurrence-v4-styles"))return;const s=document.createElement("style");s.id="recurrence-v4-styles";s.textContent=`.recurrence-box{margin-top:14px;padding:13px;border:1px solid var(--border);border-radius:11px;background:#fafcff}.recurrence-box label{margin-top:8px!important}.recurrence-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.recurrence-preview{display:block;margin-top:8px;color:var(--muted);line-height:1.35}.recurrence-hidden{display:none!important}.delete-series-modal{position:fixed;inset:0;z-index:7000;display:grid;place-items:center;padding:18px}.delete-series-backdrop{position:absolute;inset:0;background:rgba(15,23,42,.58)}.delete-series-card{position:relative;width:min(480px,100%);background:white;border-radius:16px;padding:20px;box-shadow:0 24px 70px rgba(0,0,0,.3)}.delete-series-options{display:grid;gap:9px;margin-top:14px}.delete-series-options button{padding:12px;border:1px solid var(--border);border-radius:10px;background:white;text-align:left}.delete-series-options .danger{color:var(--danger);font-weight:700}.delete-series-cancel{width:100%;margin-top:12px;padding:11px;border:0;border-radius:10px;background:#eef3fa}@media(max-width:520px){.recurrence-grid{grid-template-columns:1fr}}`;document.head.appendChild(s);}addStyles();
function markup(prefix){return `<div class="recurrence-box" data-recurrence-box="${prefix}"><label for="${prefix}Recorrencia">Repetição</label><select id="${prefix}Recorrencia"><option value="unica">Única</option><option value="fixa">Fixa</option><option value="parcelada">Parcelada</option></select><div id="${prefix}FrequenciaBox" class="recurrence-hidden"><label for="${prefix}Frequencia">Frequência</label><select id="${prefix}Frequencia">${Object.entries(FREQUENCIES).map(([v,l])=>`<option value="${v}">${l}</option>`).join("")}</select></div><div id="${prefix}ParcelasBox" class="recurrence-hidden"><div class="recurrence-grid"><div><label for="${prefix}Parcelas">Quantidade de parcelas</label><input id="${prefix}Parcelas" type="number" min="2" max="999" value="2"></div><div><label for="${prefix}ValorModo">O valor digitado é</label><select id="${prefix}ValorModo"><option value="total">Valor total</option><option value="parcela">Valor da parcela</option></select></div></div><small id="${prefix}ParcelaPreview" class="recurrence-preview"></small></div><small id="${prefix}RecorrenciaHint" class="recurrence-preview"></small></div>`;}
function setup(prefix,valueId){const type=document.getElementById(`${prefix}Recorrencia`),value=document.getElementById(valueId);if(!type)return;const refresh=()=>{const t=type.value,repeat=t!=="unica",parcel=t==="parcelada",freqEl=document.getElementById(`${prefix}Frequencia`),freq=FREQUENCIES[freqEl?.value]||"Mensal";document.getElementById(`${prefix}FrequenciaBox`)?.classList.toggle("recurrence-hidden",!repeat);document.getElementById(`${prefix}ParcelasBox`)?.classList.toggle("recurrence-hidden",!parcel);const hint=document.getElementById(`${prefix}RecorrenciaHint`);if(hint)hint.textContent=t==="unica"?"Lançamento único.":t==="fixa"?`Operação fixa ${freq.toLowerCase()}, sem data final, até você encerrar a série.`:`Parcelas repetidas com frequência ${freq.toLowerCase()}.`;if(parcel){const q=Math.max(2,Number(document.getElementById(`${prefix}Parcelas`)?.value||2)),mode=document.getElementById(`${prefix}ValorModo`)?.value||"total",v=getMoneyValue(value),preview=document.getElementById(`${prefix}ParcelaPreview`);if(preview){if(!v||v<=0)preview.textContent="Informe o valor para calcular.";else{const vals=mode==="total"?splitTotal(v,q):Array(q).fill(Math.round(v*100)/100),total=Number(vals.reduce((a,b)=>a+b,0).toFixed(2)),first=vals[0];preview.textContent=mode==="total"?`${q} parcelas · valor da parcela: ${first.toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2})} · total: ${total.toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2})}`:`${q} parcelas · valor da parcela: ${first.toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2})} · valor total: ${total.toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2})}`;}}}};type.addEventListener("change",refresh);document.getElementById(`${prefix}Frequencia`)?.addEventListener("change",refresh);document.getElementById(`${prefix}Parcelas`)?.addEventListener("input",refresh);document.getElementById(`${prefix}ValorModo`)?.addEventListener("change",refresh);value?.addEventListener("input",refresh);refresh();}
function addFields(){for(const c of [{form:"receitaForm",p:"receita",v:"receitaValor"},{form:"despesaForm",p:"despesa",v:"despesaValor"},{form:"transferForm",p:"transfer",v:"transferValor"}]){const form=document.getElementById(c.form);if(!form||document.getElementById(`${c.p}Recorrencia`))continue;form.querySelector('button[type="submit"]')?.insertAdjacentHTML("beforebegin",markup(c.p));setup(c.p,c.v);}}addFields();

const selectedText=id=>document.getElementById(id)?.selectedOptions?.[0]?.textContent?.trim()||"";
function formData(kind){const p=kind==="receita"?"receita":kind==="despesa"?"despesa":"transfer",data=document.getElementById(`${p}Data`)?.value||"",valor=getMoneyValue(document.getElementById(`${p}Valor`)),tipo=document.getElementById(`${p}Recorrencia`)?.value||"unica",frequencia=document.getElementById(`${p}Frequencia`)?.value||"mensal";let base;if(kind==="receita"||kind==="despesa")base={contaId:document.getElementById(`${p}Conta`)?.value||"",contaNome:selectedText(`${p}Conta`),categoriaId:document.getElementById(`${p}Categoria`)?.value||"",categoriaNome:selectedText(`${p}Categoria`),subcategoria:document.getElementById(`${p}Subcategoria`)?.value||"",descricao:document.getElementById(`${p}Descricao`)?.value.trim()||"",moeda:document.getElementById(`${p}Moeda`)?.value||""};else base={origemId:document.getElementById("transferOrigem")?.value||"",origemNome:selectedText("transferOrigem"),destinoId:document.getElementById("transferDestino")?.value||"",destinoNome:selectedText("transferDestino"),categoriaId:document.getElementById("transferCategoria")?.value||"",categoriaNome:selectedText("transferCategoria"),subcategoria:document.getElementById("transferSubcategoria")?.value||"",descricao:document.getElementById("transferDescricao")?.value.trim()||"",moeda:document.getElementById("transferMoeda")?.value||""};return{p,data,valor,tipo,frequencia,base,qtd:Math.max(2,Number(document.getElementById(`${p}Parcelas`)?.value||2)),modo:document.getElementById(`${p}ValorModo`)?.value||"total"};}
function validate(kind,d){if(!currentUser)return"Usuário não autenticado.";if(!d.data||!d.valor||d.valor<=0||!d.base.moeda||!d.base.categoriaId||!d.base.descricao)return"Preencha todos os campos obrigatórios.";if(kind==="transferencia"&&(!d.base.origemId||!d.base.destinoId||d.base.origemId===d.base.destinoId))return"Selecione contas diferentes.";if(kind!=="transferencia"&&!d.base.contaId)return"Selecione uma conta.";if(d.tipo!=="unica"&&!FREQUENCIES[d.frequencia])return"Selecione uma frequência válida.";return"";}

async function movements(kind,base,amount,data,meta={}){const common={categoriaId:base.categoriaId,categoriaNome:base.categoriaNome,subcategoria:base.subcategoria,descricao:base.descricao,valor:Number(amount.toFixed(2)),moeda:base.moeda,data,...parts(data),competencia:monthKey(data),serieId:meta.serieId||null,recorrenciaTipo:meta.tipo||"unica",frequencia:meta.frequencia||null,planejada:false,efetivada:true,dataEfetivacao:data,atualizadoEm:serverTimestamp()};if(kind==="receita"||kind==="despesa"){const ref=await addDoc(collection(db,"users",currentUser.uid,"contas",base.contaId,"movimentacoes"),{...common,tipo:kind,origem:kind==="receita"?"receitas":"despesas",criadoEm:serverTimestamp()});return{movimentacaoId:ref.id};}const out=await addDoc(collection(db,"users",currentUser.uid,"contas",base.origemId,"movimentacoes"),{...common,tipo:"despesa",origem:"transferencias",descricao:`Transferência: ${base.descricao}`,criadoEm:serverTimestamp()});const inn=await addDoc(collection(db,"users",currentUser.uid,"contas",base.destinoId,"movimentacoes"),{...common,tipo:"receita",origem:"transferencias",descricao:`Transferência: ${base.descricao}`,criadoEm:serverTimestamp()});return{movSaida:out.id,movEntrada:inn.id};}
async function occurrence(kind,{base,data,valor,serieId=null,tipo="unica",frequencia=null,parcelaNumero=null,parcelasTotal=null,effective=false}){const amount=Number(Number(valor).toFixed(2)),ids=effective?await movements(kind,base,amount,data,{serieId,tipo,frequencia}):{};await addDoc(collection(db,"users",currentUser.uid,COLLECTIONS[kind]),{...base,valor:amount,data,...parts(data),serieId,recorrenciaTipo:tipo,frequencia,competencia:monthKey(data),ocorrenciaChave:data,parcelaNumero,parcelasTotal,planejada:!effective,efetivada:effective,...(effective?{dataEfetivacao:data,valorEfetivado:amount}:{}),...ids,criadoEm:serverTimestamp(),atualizadoEm:serverTimestamp()});}
async function createOperation(kind,d,effectiveFirst=false){if(d.tipo==="unica"){await occurrence(kind,{base:d.base,data:d.data,valor:d.valor,effective:effectiveFirst});return;}const values=d.tipo==="parcelada"?(d.modo==="total"?splitTotal(d.valor,d.qtd):Array(d.qtd).fill(Math.round(d.valor*100)/100)):null,dates=d.tipo==="parcelada"?Array.from({length:d.qtd},(_,i)=>nextDate(d.data,d.frequencia,i)):null,total=values?Number(values.reduce((a,b)=>a+b,0).toFixed(2)):null,fim=dates?.at(-1)||null;const serie=await addDoc(collection(db,"users",currentUser.uid,"recorrencias"),{operacao:kind,tipoRecorrencia:d.tipo,frequencia:d.frequencia,inicio:d.data,fim,quantidade:d.tipo==="parcelada"?d.qtd:null,valorParcela:d.tipo==="parcelada"?values[0]:d.valor,valorTotal:total,valorModo:d.tipo==="parcelada"?d.modo:null,base:d.base,excecoes:[],ativo:true,criadoEm:serverTimestamp(),atualizadoEm:serverTimestamp()});if(d.tipo==="fixa"){await occurrence(kind,{base:d.base,data:d.data,valor:d.valor,serieId:serie.id,tipo:"fixa",frequencia:d.frequencia,effective:effectiveFirst});return;}for(let i=0;i<dates.length;i++)await occurrence(kind,{base:d.base,data:dates[i],valor:values[i],serieId:serie.id,tipo:"parcelada",frequencia:d.frequencia,parcelaNumero:i+1,parcelasTotal:d.qtd,effective:effectiveFirst&&i===0});}
function reset(kind){const p=kind==="transferencia"?"transfer":kind,form=document.getElementById(kind==="transferencia"?"transferForm":`${p}Form`);form?.reset();const type=document.getElementById(`${p}Recorrencia`);if(type){type.value="unica";type.dispatchEvent(new Event("change"));}}
for(const [kind,formId,titleId,msgId] of [["receita","receitaForm","receitaFormTitulo","receitaMensagem"],["despesa","despesaForm","despesaFormTitulo","despesaMensagem"],["transferencia","transferForm","transferFormTitle","transferMensagem"]]){document.getElementById(formId)?.addEventListener("submit",async e=>{if(/^Editar/i.test(document.getElementById(titleId)?.textContent||""))return;e.preventDefault();e.stopImmediatePropagation();const d=formData(kind),err=validate(kind,d),m=document.getElementById(msgId),quick=e.currentTarget.querySelector(`[data-quick-settle="${kind}"]`)?.checked===true;if(err){if(m){m.textContent=err;m.className="message error";}return;}try{await createOperation(kind,d,quick);if(m){m.textContent=quick?"Operação salva. A primeira ocorrência foi efetivada; as futuras permanecem previstas.":"Operação prevista criada. Use Efetivar quando ela realmente acontecer.";m.className="message success";}reset(kind);}catch(error){console.error(error);if(m){m.textContent="Não foi possível salvar a operação.";m.className="message error";}}},true);}

async function syncRecurrences(targetStart=null,targetEnd=null){if(!currentUser||syncing)return;syncing=true;try{const now=new Date(),defaultStart=`${now.getFullYear()}-${pad(now.getMonth()+1)}-01`,defaultEnd=`${now.getFullYear()}-${pad(now.getMonth()+1)}-${pad(new Date(now.getFullYear(),now.getMonth()+1,0).getDate())}`,start=targetStart||defaultStart,end=targetEnd||defaultEnd,[seriesSnap,rSnap,dSnap,tSnap]=await Promise.all([getDocs(collection(db,"users",currentUser.uid,"recorrencias")),getDocs(collection(db,"users",currentUser.uid,"receitas")),getDocs(collection(db,"users",currentUser.uid,"despesas")),getDocs(collection(db,"users",currentUser.uid,"transferencias"))]),existing={receita:rSnap.docs.map(d=>d.data()),despesa:dSnap.docs.map(d=>d.data()),transferencia:tSnap.docs.map(d=>d.data())};for(const sd of seriesSnap.docs){const series={id:sd.id,...sd.data()};if(!series.ativo||series.tipoRecorrencia!=="fixa"||!COLLECTIONS[series.operacao])continue;const exceptions=new Set(series.excecoes||[]),dates=datesInRange(series,start,end);for(const date of dates){if(exceptions.has(date)||exceptions.has(monthKey(date)))continue;if((existing[series.operacao]||[]).some(r=>r.serieId===series.id&&r.data===date))continue;await occurrence(series.operacao,{base:series.base,data:date,valor:Number(series.valorParcela||0),serieId:series.id,tipo:"fixa",frequencia:series.frequencia||"mensal"});existing[series.operacao].push({serieId:series.id,data:date});}}}catch(error){console.error("Falha ao sincronizar recorrências:",error);}finally{syncing=false;}}

function deleteModal(){return new Promise(resolve=>{document.getElementById("deleteSeriesModal")?.remove();const modal=document.createElement("div");modal.id="deleteSeriesModal";modal.className="delete-series-modal";modal.innerHTML=`<div class="delete-series-backdrop"></div><section class="delete-series-card"><h3>Excluir operação recorrente</h3><p>Escolha o alcance da exclusão.</p><div class="delete-series-options"><button data-scope="one">Apagar só esta ocorrência</button><button data-scope="all" class="danger">Apagar desde o início</button><button data-scope="future" class="danger">Apagar desta ocorrência em diante</button></div><button class="delete-series-cancel" data-scope="cancel">Cancelar</button></section>`;document.body.appendChild(modal);modal.addEventListener("click",e=>{const b=e.target.closest("[data-scope]");if(b){modal.remove();resolve(b.dataset.scope);}else if(e.target.classList.contains("delete-series-backdrop")){modal.remove();resolve("cancel");}});});}
async function removeMovements(kind,r){if(kind==="receita"||kind==="despesa"){if(r.movimentacaoId)await deleteDoc(doc(db,"users",currentUser.uid,"contas",r.contaId,"movimentacoes",r.movimentacaoId));return;}if(r.movSaida)await deleteDoc(doc(db,"users",currentUser.uid,"contas",r.origemId,"movimentacoes",r.movSaida));if(r.movEntrada)await deleteDoc(doc(db,"users",currentUser.uid,"contas",r.destinoId,"movimentacoes",r.movEntrada));}
async function deleteRoot(kind,r){await removeMovements(kind,r);await deleteDoc(doc(db,"users",currentUser.uid,COLLECTIONS[kind],r.id));}
async function deleteScope(kind,record,scope){const serieRef=doc(db,"users",currentUser.uid,"recorrencias",record.serieId),snap=await getDocs(collection(db,"users",currentUser.uid,COLLECTIONS[kind])),rows=snap.docs.map(d=>({id:d.id,...d.data()})).filter(r=>r.serieId===record.serieId);if(scope==="one"){await deleteRoot(kind,record);await updateDoc(serieRef,{excecoes:arrayUnion(record.data),atualizadoEm:serverTimestamp()});return;}if(scope==="all"){for(const r of rows)await deleteRoot(kind,r);await deleteDoc(serieRef);return;}for(const r of rows.filter(r=>r.data>=record.data))await deleteRoot(kind,r);await updateDoc(serieRef,{fim:previousDay(record.data),ativo:false,atualizadoEm:serverTimestamp()});}
const deleteMap=[{selector:".delete-revenue",kind:"receita"},{selector:".delete-expense",kind:"despesa"},{selector:".delete-transfer",kind:"transferencia"}];
document.addEventListener("click",async e=>{for(const item of deleteMap){const btn=e.target.closest(item.selector);if(!btn||!currentUser)continue;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const snap=await getDoc(doc(db,"users",currentUser.uid,COLLECTIONS[item.kind],btn.dataset.id));if(!snap.exists())return;const record={id:snap.id,...snap.data()};if(!record.serieId){if(!confirm("Tem certeza que deseja apagar esta operação? Esta ação não pode ser desfeita."))return;try{await deleteRoot(item.kind,record);}catch(error){console.error(error);alert("Não foi possível apagar a operação.");}return;}const scope=await deleteModal();if(!scope||scope==="cancel")return;const labels={one:"somente esta ocorrência",all:"toda a série desde o início",future:"esta ocorrência e todas as seguintes"};if(!confirm(`Tem certeza que deseja apagar ${labels[scope]}? Esta ação não pode ser desfeita.`))return;try{await deleteScope(item.kind,record,scope);}catch(error){console.error(error);alert("Não foi possível concluir a exclusão.");}return;}},true);

onAuthStateChanged(auth,user=>{currentUser=user;if(user)setTimeout(()=>syncRecurrences(),100);});
window.addEventListener("period-change",e=>{if(!currentUser)return;const d=e.detail||{};if(!["dashboard","receitas","despesas","transferencias"].includes(d.viewId))return;setTimeout(()=>syncRecurrences(d.start||null,d.end||null),40);});
export { syncRecurrences, splitTotal, nextDate, FREQUENCIES };
