import { auth, db } from "./firebase.js";
import { formatMoney, getMoneyValue, resetMoneyField } from "./money.js";
import { addDoc, collection, deleteDoc, doc, getDocs, onSnapshot, orderBy, query, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";

const content=document.getElementById("content"),placeholder=document.getElementById("placeholderView");
const style=document.createElement("style");style.textContent=`
.module-grid{display:grid;grid-template-columns:minmax(300px,380px) minmax(0,1fr);gap:16px}.module-row{display:flex;justify-content:space-between;gap:14px;padding:12px 0;border-bottom:1px solid var(--border)}.module-row small{display:block;color:var(--muted);margin-top:3px}.module-row-actions{display:flex;gap:8px;justify-content:flex-end}.module-row-actions button{border:0;background:transparent;color:var(--danger)}.report-cards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.report-card{padding:16px;border:1px solid var(--border);border-radius:12px;background:#fff}.report-card small{display:block;color:var(--muted);margin-bottom:6px}.settings-block{max-width:560px}.settings-block select{width:100%;padding:11px;border:1px solid var(--border);border-radius:9px;background:#fff}.settings-note{margin-top:9px;color:var(--muted);font-size:.86rem}@media(max-width:900px){.module-grid,.report-cards{grid-template-columns:1fr}}
`;document.head.appendChild(style);

function addView(id,html){let v=document.getElementById(id);if(v)v.remove();v=document.createElement("div");v.id=id;v.className="app-view hidden";v.innerHTML=html;content.insertBefore(v,placeholder);return v;}
addView("orcamentos",`<div class="module-grid"><article class="panel"><h3>Novo orçamento</h3><form id="budgetForm" class="account-form"><label>Categoria</label><input id="budgetCategory" maxlength="60" placeholder="Ex.: Alimentação" required><label>Mês</label><input id="budgetMonth" type="month" required><label>Limite</label><div class="money-field" data-money-field><div class="money-input-row"><select id="budgetCurrency" data-money-currency><option>BRL</option><option>USD</option><option>EUR</option></select><input id="budgetValue" data-money-input type="text" inputmode="decimal" value="0,00"><button type="button" class="calculator-toggle" data-money-calculator>🧮</button></div></div><button class="primary form-button" type="submit">Salvar orçamento</button><p id="budgetMsg" class="message"></p></form></article><article class="panel"><h3>Orçamentos</h3><div id="budgetList" class="empty-state">Nenhum orçamento cadastrado.</div></article></div>`);
addView("objetivos",`<div class="module-grid"><article class="panel"><h3>Novo objetivo</h3><form id="goalForm" class="account-form"><label>Objetivo</label><input id="goalName" maxlength="80" placeholder="Ex.: Reserva de emergência" required><label>Prazo</label><input id="goalDate" type="date"><label>Valor alvo</label><div class="money-field" data-money-field><div class="money-input-row"><select id="goalCurrency" data-money-currency><option>BRL</option><option>USD</option><option>EUR</option></select><input id="goalValue" data-money-input type="text" inputmode="decimal" value="0,00"><button type="button" class="calculator-toggle" data-money-calculator>🧮</button></div></div><button class="primary form-button" type="submit">Salvar objetivo</button><p id="goalMsg" class="message"></p></form></article><article class="panel"><h3>Objetivos</h3><div id="goalList" class="empty-state">Nenhum objetivo cadastrado.</div></article></div>`);
addView("relatorios",`<article class="panel"><h3>Resumo financeiro</h3><div class="report-cards"><div class="report-card"><small>Receitas efetivadas</small><strong id="reportIncome" class="financial-value">R$ 0,00</strong></div><div class="report-card"><small>Despesas efetivadas</small><strong id="reportExpense" class="financial-value">R$ 0,00</strong></div><div class="report-card"><small>Resultado</small><strong id="reportResult" class="financial-value">R$ 0,00</strong></div></div><p class="settings-note">Este resumo usa apenas operações efetivadas. Os filtros avançados e exportações serão refinados na revisão.</p></article>`);
addView("configuracoes",`<article class="panel settings-block"><h3>Configurações</h3><label for="mainCurrency">Moeda principal do aplicativo</label><select id="mainCurrency"><option value="BRL">BRL · Real</option><option value="USD">USD · Dólar</option><option value="EUR">EUR · Euro</option><option value="GBP">GBP · Libra</option><option value="JPY">JPY · Iene</option><option value="CHF">CHF · Franco suíço</option><option value="CAD">CAD · Dólar canadense</option><option value="AUD">AUD · Dólar australiano</option></select><p class="settings-note">A moeda principal é usada nos totais consolidados e nos títulos da Dashboard.</p></article>`);

const mainCurrency=document.getElementById("mainCurrency");mainCurrency.value=localStorage.getItem("app-financas-main-currency")||"BRL";mainCurrency.addEventListener("change",()=>{localStorage.setItem("app-financas-main-currency",mainCurrency.value);window.dispatchEvent(new CustomEvent("main-currency-change",{detail:{currency:mainCurrency.value}}));});

let user=null,budgets=[],goals=[],revenues=[],expenses=[],stops=[];
function esc(v=""){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]);}
function msg(id,text,type="success"){const e=document.getElementById(id);e.textContent=text;e.className=`message ${type}`;}
function renderBudgets(){const el=document.getElementById("budgetList");el.className=budgets.length?"":"empty-state";el.innerHTML=budgets.length?budgets.map(r=>`<div class="module-row"><div><strong>${esc(r.categoria)}</strong><small>${esc(r.mes||"")}</small></div><div><strong>${formatMoney(r.valor||0,r.moeda||"BRL")}</strong><div class="module-row-actions"><button data-budget-delete="${r.id}" type="button">Excluir</button></div></div></div>`).join(""):"Nenhum orçamento cadastrado.";}
function renderGoals(){const el=document.getElementById("goalList");el.className=goals.length?"":"empty-state";el.innerHTML=goals.length?goals.map(r=>`<div class="module-row"><div><strong>${esc(r.nome)}</strong><small>${r.prazo?`Prazo: ${esc(r.prazo)}`:"Sem prazo"}</small></div><div><strong>${formatMoney(r.valor||0,r.moeda||"BRL")}</strong><div class="module-row-actions"><button data-goal-delete="${r.id}" type="button">Excluir</button></div></div></div>`).join(""):"Nenhum objetivo cadastrado.";}
function renderReports(){const r=revenues.filter(x=>x.efetivada===true).reduce((s,x)=>s+((x.moeda||"BRL")==="BRL"?Number(x.valor||0):0),0),d=expenses.filter(x=>x.efetivada===true).reduce((s,x)=>s+((x.moeda||"BRL")==="BRL"?Number(x.valor||0):0),0);document.getElementById("reportIncome").textContent=formatMoney(r,"BRL");document.getElementById("reportExpense").textContent=formatMoney(d,"BRL");document.getElementById("reportResult").textContent=formatMoney(r-d,"BRL");}

document.getElementById("budgetForm").addEventListener("submit",async e=>{e.preventDefault();if(!user)return;const valor=getMoneyValue(document.getElementById("budgetValue"));if(valor<=0)return msg("budgetMsg","Informe um valor maior que zero.","error");await addDoc(collection(db,"users",user.uid,"orcamentos"),{categoria:document.getElementById("budgetCategory").value.trim(),mes:document.getElementById("budgetMonth").value,valor,moeda:document.getElementById("budgetCurrency").value,criadoEm:serverTimestamp()});e.target.reset();resetMoneyField(document.getElementById("budgetValue"),"BRL");msg("budgetMsg","Orçamento cadastrado.");});
document.getElementById("goalForm").addEventListener("submit",async e=>{e.preventDefault();if(!user)return;const valor=getMoneyValue(document.getElementById("goalValue"));if(valor<=0)return msg("goalMsg","Informe um valor maior que zero.","error");await addDoc(collection(db,"users",user.uid,"objetivos"),{nome:document.getElementById("goalName").value.trim(),prazo:document.getElementById("goalDate").value||"",valor,moeda:document.getElementById("goalCurrency").value,criadoEm:serverTimestamp()});e.target.reset();resetMoneyField(document.getElementById("goalValue"),"BRL");msg("goalMsg","Objetivo cadastrado.");});
document.addEventListener("click",async e=>{const b=e.target.closest("[data-budget-delete]"),g=e.target.closest("[data-goal-delete]");if(b&&user&&confirm("Tem certeza que deseja excluir este orçamento?"))await deleteDoc(doc(db,"users",user.uid,"orcamentos",b.dataset.budgetDelete));if(g&&user&&confirm("Tem certeza que deseja excluir este objetivo?"))await deleteDoc(doc(db,"users",user.uid,"objetivos",g.dataset.goalDelete));});

onAuthStateChanged(auth,current=>{user=current;stops.forEach(s=>s());stops=[];budgets=[];goals=[];revenues=[];expenses=[];renderBudgets();renderGoals();renderReports();if(!current)return;[["orcamentos",v=>{budgets=v;renderBudgets();}],["objetivos",v=>{goals=v;renderGoals();}],["receitas",v=>{revenues=v;renderReports();}],["despesas",v=>{expenses=v;renderReports();}]].forEach(([name,set])=>{const ref=name==="receitas"||name==="despesas"?query(collection(db,"users",current.uid,name),orderBy("data","desc")):collection(db,"users",current.uid,name);stops.push(onSnapshot(ref,s=>set(s.docs.map(d=>({id:d.id,...d.data()}))),()=>set([])));});});
