import { auth, db } from "./firebase.js";
import { formatMoney, getMoneyValue, resetMoneyField, setMoneyValue } from "./money.js";
import { getCategoriesFor } from "./categorias.js";
import { createMonthNavigator, getPeriod } from "./period.js";
import { addDoc, collection, deleteDoc, doc, getDocs, onSnapshot, orderBy, query, serverTimestamp, updateDoc } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";

const content=document.getElementById("content"),placeholder=document.getElementById("placeholderView");
let view=document.getElementById("transferencias");if(view)view.remove();
view=document.createElement("div");view.id="transferencias";view.className="app-view hidden";
view.innerHTML=`<div id="transferenciasMonthNavigator"></div><div class="page-grid transfer-layout"><article class="panel"><h3 id="transferFormTitle">Nova transferência</h3><form id="transferForm" class="account-form"><label>Conta de origem</label><select id="transferOrigem" required></select><label>Conta de destino</label><select id="transferDestino" required></select><div class="field-with-action"><div><label>Categoria</label><select id="transferCategoria" required></select></div><button id="addTransferCategoria" type="button" class="small-action">+ Categoria</button></div><label>Subcategoria</label><select id="transferSubcategoria"><option value="">Sem subcategoria</option></select><label>Descrição</label><input id="transferDescricao" maxlength="80" placeholder="Ex.: Transferência para reserva" required><label>Data</label><input id="transferData" type="date" required><label>Valor</label><div class="money-field" data-money-field><div class="money-input-row"><select id="transferMoeda" data-money-currency></select><input id="transferValor" data-money-input type="text" inputmode="decimal" value="0,00"><button type="button" class="calculator-toggle" data-money-calculator>🧮</button></div></div><small id="transferCurrencyHint">Escolha as duas contas para ver as moedas em comum.</small><button id="transferSalvar" class="primary form-button" type="submit">Salvar transferência</button><button id="transferCancelar" class="secondary form-button hidden" type="button">Cancelar edição</button><p id="transferMensagem" class="message"></p></form></article><article class="panel"><div class="panel-heading"><div><h3>Transferências do mês</h3><small id="totalTransferencias"></small></div></div><div class="dynamic-filter-grid"><select id="filtroTransferConta"></select><select id="filtroTransferCategoria"></select><select id="filtroTransferMoeda"></select></div><div id="listaTransferencias"><div class="empty-state">Nenhuma transferência cadastrada.</div></div></article></div>`;
content.insertBefore(view,placeholder);createMonthNavigator("transferencias",document.getElementById("transferenciasMonthNavigator"));

const style=document.createElement("style");style.textContent=`.transfer-layout{grid-template-columns:minmax(300px,380px) minmax(0,1fr)}.transfer-layout .field-with-action{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:end}.transfer-layout .small-action{height:44px;padding:0 10px;border:1px solid var(--primary);border-radius:9px;background:white;color:var(--primary);font-weight:700}.transfer-item{display:flex;justify-content:space-between;gap:16px;padding:14px 0;border-bottom:1px solid var(--border)}.transfer-item span{display:block;margin-top:4px;color:var(--muted);font-size:.88rem}.transfer-value{text-align:right}.transfer-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:6px}.transfer-actions button{border:0;background:transparent}.edit-transfer{color:var(--primary)}.delete-transfer{color:var(--danger)}@media(max-width:980px){.transfer-layout{grid-template-columns:1fr}}`;document.head.appendChild(style);

const $=id=>document.getElementById(id);const form=$("transferForm"),origem=$("transferOrigem"),destino=$("transferDestino"),categoria=$("transferCategoria"),subcategoria=$("transferSubcategoria"),moeda=$("transferMoeda"),valorInput=$("transferValor"),lista=$("listaTransferencias"),msg=$("transferMensagem"),titulo=$("transferFormTitle"),salvar=$("transferSalvar"),cancelar=$("transferCancelar"),hint=$("transferCurrencyHint"),fConta=$("filtroTransferConta"),fCat=$("filtroTransferCategoria"),fMoeda=$("filtroTransferMoeda"),total=$("totalTransferencias");
let user=null,accounts=[],transfers=[],editing=null,stop=null;
const esc=(v="")=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]);
const today=()=>new Date().toISOString().slice(0,10);const parts=data=>{const d=new Date(`${data}T12:00:00`),m=d.getMonth()+1;return{ano:d.getFullYear(),mes:m,trimestre:Math.ceil(m/3),semestre:m<=6?1:2,dataChave:data};};const cats=()=>getCategoriesFor("transferencia");
async function currencies(acc){const snap=await getDocs(collection(db,"users",user.uid,"contas",acc.id,"moedas"));return [...new Set([acc.moeda||"BRL",...snap.docs.map(d=>d.data().codigo)])];}
async function refreshCurrencies(preferred=""){const a=accounts.find(x=>x.id===origem.value),b=accounts.find(x=>x.id===destino.value);if(!a||!b){moeda.innerHTML="";hint.textContent="Escolha as duas contas para ver as moedas em comum.";return;}const [ca,cb]=await Promise.all([currencies(a),currencies(b)]),common=ca.filter(x=>cb.includes(x));moeda.innerHTML=common.map(x=>`<option value="${x}">${x}</option>`).join("");if(preferred&&common.includes(preferred))moeda.value=preferred;hint.textContent=common.length?"A transferência usa uma moeda disponível nas duas contas.":"As contas selecionadas não possuem uma moeda em comum.";}
function renderAccounts(){const opts=accounts.map(a=>`<option value="${a.id}">${esc(a.nome)}</option>`).join("");origem.innerHTML=`<option value="">Selecione...</option>${opts}`;destino.innerHTML=`<option value="">Selecione...</option>${opts}`;}
function renderCats(pref="",sub=""){categoria.innerHTML=`<option value="">Selecione...</option>${cats().map(c=>`<option value="${c.id}">${esc(c.nome)}</option>`).join("")}`;if(pref)categoria.value=pref;const c=cats().find(x=>x.id===categoria.value),subs=c?.subcategorias||[];subcategoria.innerHTML=`<option value="">Sem subcategoria</option>${subs.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join("")}`;if(subs.includes(sub))subcategoria.value=sub;}
function monthRows(){const p=getPeriod("transferencias");return transfers.filter(t=>t.data>=p.start&&t.data<=p.end);}function filtered(){return monthRows().filter(t=>(!fConta.value||(t.origemId===fConta.value||t.destinoId===fConta.value))&&(!fCat.value||t.categoriaId===fCat.value)&&(!fMoeda.value||t.moeda===fMoeda.value));}
function rebuildFilters(){const rows=monthRows(),keep=[fConta.value,fCat.value,fMoeda.value],am=new Map(),cm=new Map();rows.forEach(r=>{am.set(r.origemId,r.origemNome);am.set(r.destinoId,r.destinoNome);cm.set(r.categoriaId,r.categoriaNome);});const ms=[...new Set(rows.map(r=>r.moeda))].sort();fConta.innerHTML=`<option value="">Todas as contas</option>${[...am].map(([v,l])=>`<option value="${v}">${esc(l)}</option>`).join("")}`;fCat.innerHTML=`<option value="">Todas as categorias</option>${[...cm].map(([v,l])=>`<option value="${v}">${esc(l)}</option>`).join("")}`;fMoeda.innerHTML=`<option value="">Todas as moedas</option>${ms.map(v=>`<option value="${v}">${v}</option>`).join("")}`;[fConta,fCat,fMoeda].forEach((el,i)=>{if([...el.options].some(o=>o.value===keep[i]))el.value=keep[i];});}
function render(){rebuildFilters();const rows=filtered(),sums=new Map();rows.forEach(r=>sums.set(r.moeda,(sums.get(r.moeda)||0)+Number(r.valor||0)));total.textContent=[...sums].map(([m,v])=>formatMoney(v,m)).join(" · ")||"Sem transferências no período";lista.innerHTML=rows.length?rows.map(r=>`<article class="transfer-item"><div><strong>${esc(r.descricao)}</strong><span>${esc(r.origemNome)} → ${esc(r.destinoNome)} · ${esc(r.categoriaNome||"")} ${r.subcategoria?`› ${esc(r.subcategoria)}`:""} · ${esc(r.data)}</span></div><div class="transfer-value"><strong>${formatMoney(r.valor,r.moeda)}</strong><div class="transfer-actions"><button class="edit-transfer" data-id="${r.id}" type="button">Editar</button><button class="delete-transfer" data-id="${r.id}" data-out="${r.movSaida||""}" data-in="${r.movEntrada||""}" data-origin="${r.origemId}" data-dest="${r.destinoId}" type="button">Excluir</button></div></div></article>`).join(""):'<div class="empty-state">Nenhuma transferência neste mês.</div>';}
function reset(){editing=null;form.reset();titulo.textContent="Nova transferência";salvar.textContent="Salvar transferência";cancelar.classList.add("hidden");const p=getPeriod("transferencias");$("transferData").value=(today()>=p.start&&today()<=p.end)?today():p.start;moeda.innerHTML="";renderCats();resetMoneyField(valorInput,"BRL");msg.textContent="";hint.textContent="Escolha as duas contas para ver as moedas em comum.";}
async function edit(id){const r=transfers.find(x=>x.id===id);if(!r)return;editing=r;titulo.textContent="Editar transferência";salvar.textContent="Salvar alterações";cancelar.classList.remove("hidden");origem.value=r.origemId;destino.value=r.destinoId;await refreshCurrencies(r.moeda);renderCats(r.categoriaId,r.subcategoria);$("transferDescricao").value=r.descricao||"";$("transferData").value=r.data;setMoneyValue(valorInput,Number(r.valor||0));}
origem.addEventListener("change",()=>refreshCurrencies());destino.addEventListener("change",()=>refreshCurrencies());categoria.addEventListener("change",()=>renderCats(categoria.value));$("addTransferCategoria").addEventListener("click",()=>window.dispatchEvent(new CustomEvent("open-category-manager",{detail:{operacao:"transferencia"}})));window.addEventListener("categories-updated",()=>{renderCats(categoria.value,subcategoria.value);render();});window.addEventListener("period-change",e=>{if(e.detail.viewId==="transferencias"){reset();render();}});[fConta,fCat,fMoeda].forEach(el=>el.addEventListener("change",render));cancelar.addEventListener("click",reset);
lista.addEventListener("click",async e=>{const eb=e.target.closest(".edit-transfer"),dbtn=e.target.closest(".delete-transfer");if(eb)return edit(eb.dataset.id);if(!dbtn||!confirm("Excluir esta transferência?"))return;await deleteDoc(doc(db,"users",user.uid,"transferencias",dbtn.dataset.id));if(dbtn.dataset.out)await deleteDoc(doc(db,"users",user.uid,"contas",dbtn.dataset.origin,"movimentacoes",dbtn.dataset.out));if(dbtn.dataset.in)await deleteDoc(doc(db,"users",user.uid,"contas",dbtn.dataset.dest,"movimentacoes",dbtn.dataset.in));if(editing?.id===dbtn.dataset.id)reset();});
form.addEventListener("submit",async e=>{e.preventDefault();const a=accounts.find(x=>x.id===origem.value),b=accounts.find(x=>x.id===destino.value),c=cats().find(x=>x.id===categoria.value),v=getMoneyValue(valorInput),data=$("transferData").value,descricao=$("transferDescricao").value.trim(),m=moeda.value,sub=subcategoria.value;if(!a||!b||a.id===b.id){msg.textContent="Selecione contas de origem e destino diferentes.";msg.className="message error";return;}if(!c||!m||!descricao||!data||v<=0){msg.textContent="Preencha todos os campos obrigatórios.";msg.className="message error";return;}const p=parts(data),base={categoriaId:c.id,categoriaNome:c.nome,subcategoria:sub,descricao,valor:v,moeda:m,data,...p,origem:"transferencias",atualizadoEm:serverTimestamp()};try{let movSaida="",movEntrada="";if(editing){if(editing.movSaida)await deleteDoc(doc(db,"users",user.uid,"contas",editing.origemId,"movimentacoes",editing.movSaida));if(editing.movEntrada)await deleteDoc(doc(db,"users",user.uid,"contas",editing.destinoId,"movimentacoes",editing.movEntrada));}const out=await addDoc(collection(db,"users",user.uid,"contas",a.id,"movimentacoes"),{...base,tipo:"despesa",descricao:`Transferência: ${descricao}`,criadoEm:serverTimestamp()});const inn=await addDoc(collection(db,"users",user.uid,"contas",b.id,"movimentacoes"),{...base,tipo:"receita",descricao:`Transferência: ${descricao}`,criadoEm:serverTimestamp()});movSaida=out.id;movEntrada=inn.id;const record={origemId:a.id,origemNome:a.nome,destinoId:b.id,destinoNome:b.nome,categoriaId:c.id,categoriaNome:c.nome,subcategoria:sub,descricao,valor:v,moeda:m,data,...p,movSaida,movEntrada,atualizadoEm:serverTimestamp()};if(editing)await updateDoc(doc(db,"users",user.uid,"transferencias",editing.id),record);else await addDoc(collection(db,"users",user.uid,"transferencias"),{...record,criadoEm:serverTimestamp()});reset();msg.textContent=editing?"Transferência atualizada.":"Transferência realizada.";msg.className="message success";}catch(err){console.error(err);msg.textContent="Não foi possível salvar a transferência.";msg.className="message error";}});
onAuthStateChanged(auth,async current=>{user=current;if(stop)stop();transfers=[];render();if(!current)return;const snap=await getDocs(collection(db,"users",current.uid,"contas"));accounts=snap.docs.map(d=>({id:d.id,...d.data()}));renderAccounts();renderCats();reset();stop=onSnapshot(query(collection(db,"users",current.uid,"transferencias"),orderBy("data","desc")),s=>{transfers=s.docs.map(d=>({id:d.id,...d.data()}));render();});});