import { chromium } from 'playwright';
const BASE='https://paes2005-design.github.io/App_Financas/';
const EMAIL='qa.app.financas.automation@gmail.com', PASSWORD='QaFinancas2026!';
const tag=Date.now().toString().slice(-6), failures=[], pageErrors=[];
const browser=await chromium.launch({headless:true}); const page=await browser.newPage({viewport:{width:1365,height:900}});
page.on('pageerror',e=>pageErrors.push(e.message));
async function check(name,fn){try{await fn();console.log(`PASS ${name}`);}catch(e){failures.push(`${name}: ${e.message}`);console.error(`FAIL ${name}: ${e.message}`);}}
async function vis(s,t=12000){await page.locator(s).waitFor({state:'visible',timeout:t});}
async function nav(id){await page.locator(`.nav-item[data-page="${id}"]`).click();await vis(`#${id}`);}
async function choose(sel,text){await page.waitForFunction(({sel,text})=>[...(document.querySelector(sel)?.options||[])].some(o=>o.textContent.includes(text)),{sel,text},{timeout:12000});const o=page.locator(`${sel} option`).filter({hasText:text}).first();await page.locator(sel).selectOption(await o.getAttribute('value'));}
async function login(){await page.goto(BASE,{waitUntil:'domcontentloaded',timeout:30000});await page.locator('#loading').waitFor({state:'hidden',timeout:15000}).catch(()=>{});if(await page.locator('#appPage').isVisible())return;await vis('#loginPage');await page.fill('#email',EMAIL);await page.fill('#password',PASSWORD);await page.click('#btnCadastrar');await page.waitForTimeout(1200);if(!(await page.locator('#appPage').isVisible())){await page.fill('#email',EMAIL);await page.fill('#password',PASSWORD);await page.click('#btnLogin');}await vis('#appPage',15000);}
async function ensureAccount(name,balance){await nav('contas');if((await page.locator('#listaContas').innerText()).includes(name))return;await page.click('#bankPickerTrigger');await page.locator('.custom-bank-option').click();await page.fill('#contaNomeLivre',name);await page.fill('#contaSaldoInicial',balance);await page.click('#contaForm button[type=submit]');await page.waitForFunction(n=>document.querySelector('#listaContas')?.innerText.includes(n),name,{timeout:12000});}
async function ensureCategory(){await nav('categorias');if((await page.locator('#categoryList').innerText()).includes('QA Geral'))return;await page.selectOption('#categoryOperation','todos');await page.fill('#categoryName','QA Geral');await page.fill('#categorySubcategories','Teste, Assinatura');await page.click('#categorySubmit');await page.waitForFunction(()=>document.querySelector('#categoryList')?.innerText.includes('QA Geral'),{timeout:12000});}
async function returnCurrentMonth(view){const navSel=`#${view}MonthNavigator`;if(await page.locator(`${navSel} [data-month-current]`).count())await page.click(`${navSel} [data-month-current]`);await page.waitForTimeout(450);}

await check('autenticação/criação da conta de teste',login);
await check('navegação em todos os 11 módulos',async()=>{for(const id of ['dashboard','contas','receitas','despesas','transferencias','cartoes','categorias','orcamentos','objetivos','relatorios','configuracoes'])await nav(id);});
await check('busca visual de bancos',async()=>{await nav('contas');await page.click('#bankPickerTrigger');await page.fill('#bankSearch','BTG');await vis('.bank-option[data-bank-id="btg"]');await page.click('.bank-option[data-bank-id="btg"]');});
await check('criar/ler contas de teste',async()=>{await ensureAccount('QA Conta A','1000,00');await ensureAccount('QA Conta B','500,00');});
await page.reload({waitUntil:'domcontentloaded'});await page.locator('#loading').waitFor({state:'hidden',timeout:15000}).catch(()=>{});await vis('#appPage',15000);
await check('categorias e subcategorias',ensureCategory);

await check('ordem descrição → valor → repetição em todas operações',async()=>{for(const cfg of [{view:'receitas',form:'receitaForm',desc:'receitaDescricao',value:'receitaValor',rec:'receitaRecorrencia'},{view:'despesas',form:'despesaForm',desc:'despesaDescricao',value:'despesaValor',rec:'despesaRecorrencia'},{view:'transferencias',form:'transferForm',desc:'transferDescricao',value:'transferValor',rec:'transferRecorrencia'}]){await nav(cfg.view);const ok=await page.evaluate(c=>{const f=document.getElementById(c.form),d=document.getElementById(c.desc),v=document.getElementById(c.value)?.closest('.money-field'),r=document.getElementById(c.rec)?.closest('.recurrence-box');if(!f||!d||!v||!r)return false;const children=[...f.children];return children.indexOf(d)>-1&&children.indexOf(v)>children.indexOf(d)&&children.indexOf(r)>children.indexOf(v);},cfg);if(!ok)throw new Error(`ordem incorreta em ${cfg.view}`);}});

const histDesc=`QA Histórico ${tag}`;
await check('receita prevista + histórico inteligente + menu ⋮ + efetivar',async()=>{await nav('receitas');await page.fill('#receitaDescricao',histDesc);await page.fill('#receitaValor','123,45');await choose('#receitaConta','QA Conta A');await choose('#receitaCategoria','QA Geral');await page.selectOption('#receitaSubcategoria',{label:'Teste'}).catch(()=>{});await page.click('#salvarReceita');await page.waitForFunction(t=>document.querySelector('#listaReceitas')?.innerText.includes(t),histDesc,{timeout:10000});const item=page.locator('.transaction-item').filter({hasText:histDesc}).first();const txt=await item.innerText();if(!/\d{2}\/\d{2}\/\d{4}/.test(txt))throw new Error('data não aparece em DD/MM/AAAA');await page.waitForFunction(t=>[...(document.querySelector('#history-receita-descriptions')?.options||[])].some(o=>o.value===t),histDesc,{timeout:8000});await page.fill('#receitaDescricao','');await page.fill('#receitaValor','0,00');await page.fill('#receitaDescricao',histDesc);await page.waitForTimeout(450);const auto=await page.locator('#receitaValor').inputValue();if(!auto.includes('123'))throw new Error(`histórico não recuperou valor: ${auto}`);await item.locator('.txn-more').click();const menu=item.locator('.txn-menu.open');if(!(await menu.innerText()).includes('Efetivar'))throw new Error('menu ⋮ não oferece Efetivar');await menu.getByText('Efetivar').click();await vis('#settlementModal');page.once('dialog',d=>d.accept());await page.click('#settlementModal .settlement-confirm');await page.waitForTimeout(900);});

const parcelDesc=`QA Parcelada ${tag}`;
await check('parcelado diário: total/parcela e centavos exatos',async()=>{await nav('despesas');await page.fill('#despesaDescricao',parcelDesc);await page.fill('#despesaValor','1000,00');await choose('#despesaConta','QA Conta A');await choose('#despesaCategoria','QA Geral');await page.selectOption('#despesaRecorrencia','parcelada');await page.selectOption('#despesaFrequencia','diaria');await page.fill('#despesaParcelas','3');await page.selectOption('#despesaValorModo','total');const preview=await page.locator('#despesaParcelaPreview').innerText();if(!preview.includes('333,34')||!preview.includes('1.000,00'))throw new Error(`preview incorreto: ${preview}`);await page.click('#salvarDespesa');await page.waitForTimeout(1300);const rows=page.locator('.expense-item').filter({hasText:parcelDesc});if(await rows.count()<3)throw new Error(`esperadas 3 parcelas no período, obtido ${await rows.count()}`);});

const fixedDesc=`QA Fixa ${tag}`;
await check('fixa semanal gera ocorrências sem projetar para trás',async()=>{await nav('despesas');await page.fill('#despesaDescricao',fixedDesc);await page.fill('#despesaValor','25,00');await choose('#despesaConta','QA Conta A');await choose('#despesaCategoria','QA Geral');await page.selectOption('#despesaRecorrencia','fixa');await page.selectOption('#despesaFrequencia','semanal');await page.click('#salvarDespesa');await page.waitForTimeout(700);await page.click('#despesasMonthNavigator [data-month-prev]');await returnCurrentMonth('despesas');await page.waitForTimeout(1200);const n=await page.locator('.expense-item').filter({hasText:fixedDesc}).count();if(n<3)throw new Error(`fixa semanal não sincronizou o mês: ${n} ocorrência(s)`);});

await check('exclusão recorrente pergunta escopo antes da certeza',async()=>{await nav('despesas');const item=page.locator('.expense-item').filter({hasText:parcelDesc}).first();await item.locator('.txn-more').click();await item.locator('.txn-menu.open').getByText('Excluir').click();await vis('#deleteSeriesModal');if(!(await page.locator('#deleteSeriesModal').innerText()).includes('Apagar só esta ocorrência'))throw new Error('modal de escopo ausente');await page.click('#deleteSeriesModal [data-scope="one"]');page.once('dialog',d=>d.dismiss());await page.waitForTimeout(250);});

await check('transferência parcelada/fixa oferece seis frequências',async()=>{await nav('transferencias');const opts=await page.locator('#transferFrequencia option').allTextContents();for(const x of ['Diária','Semanal','Mensal','Trimestral','Semestral','Anual'])if(!opts.includes(x))throw new Error(`frequência ausente: ${x}`);await page.fill('#transferDescricao',`QA Transfer ${tag}`);await page.fill('#transferValor','10,00');await choose('#transferOrigem','QA Conta A');await choose('#transferDestino','QA Conta B');await choose('#transferCategoria','QA Geral');await page.selectOption('#transferRecorrencia','unica');await page.click('#transferSalvar');await page.waitForFunction(t=>document.querySelector('#listaTransferencias')?.innerText.includes(t),`QA Transfer ${tag}`,{timeout:10000});});

let cardName=`QA Card ${tag}`;
await check('cartão: fixa/parcelada, frequência e competência de fatura',async()=>{await nav('cartoes');await page.fill('#cardNome',cardName);await choose('#cardConta','QA Conta A');await page.waitForFunction(()=>document.querySelector('#cardMoeda')?.options.length>0,{timeout:10000});await page.fill('#cardLimite','1500,00');await page.fill('#cardFechamento','20');await page.fill('#cardVencimento','28');await page.click('#cardSalvar');await page.waitForFunction(t=>document.querySelector('#listaCartoes')?.innerText.includes(t),cardName,{timeout:10000});await page.locator('.card-expense-open').click();await vis('#cardExpenseForm');if(!await page.locator('#cardExpenseType option[value="fixa"]').count())throw new Error('cartão sem tipo Fixa');await page.fill('#cardExpenseDescription',`QA Compra ${tag}`);await page.fill('#cardExpenseValue','100,00');await choose('#cardExpenseCard',cardName);await choose('#cardExpenseCategory','QA Geral');await page.selectOption('#cardExpenseType','parcelada');await page.selectOption('#cardExpenseFrequency','mensal');await page.fill('#cardExpenseInstallments','3');await page.selectOption('#cardExpenseValueMode','total');await page.click('#cardExpenseSave');await page.waitForTimeout(1200);if(!(await page.locator('#cardExpenseList').innerText()).includes(`QA Compra ${tag}`))throw new Error('despesa de cartão não registrada');});

await check('dashboard: cotação só no i, hover do saldo e sem efetivado duplicado',async()=>{await nav('dashboard');await vis('#saldoTotal');const display=await page.locator('#exchangeStatus').evaluate(el=>getComputedStyle(el).display);if(display!=='none')throw new Error('cotação ainda aparece fora do i');const saldoBtn=page.locator('#saldoTotal').closest('.card').locator('.info-button');await saldoBtn.hover();await page.waitForTimeout(120);if(await page.locator('#saldoInfoDetalhes').evaluate(el=>el.classList.contains('hidden')))throw new Error('i do saldo não abre no hover');for(const id of ['dashboardRevenueMini','dashboardExpenseMini','dashboardResultMini']){const first=page.locator(`#${id} .balance-mini-item`).first();if(await first.evaluate(el=>getComputedStyle(el).display)!=='none')throw new Error(`efetivado duplicado visível em ${id}`);}await page.click('#dashboardValueToggle');await page.click('#dashboardValueToggle');await page.click('.dashboard-settings-button');await vis('.dashboard-settings-panel');await page.click('.dashboard-settings-back');for(const id of ['chart-cashChart','chart-compareChart','chart-categoryChart'])if(!(await page.locator(`#${id}`).count()))throw new Error(`gráfico ausente: ${id}`);});
await check('filtros em receitas/despesas/transferências',async()=>{for(const id of ['receitas','despesas','transferencias']){await nav(id);await page.locator(`#${id} .filter-launch`).click();await vis('.filter-modal:not(.hidden)');await page.locator('.filter-modal:not(.hidden) [data-period]').selectOption('custom');await page.locator('.filter-modal:not(.hidden) .filter-close').click();}});
await check('detalhes informativos',async()=>{for(const id of ['receitas','despesas','transferencias']){await nav(id);const b=page.locator(`[data-insight-open="${id}"]`);await b.click();await vis('.insight-modal:not(.hidden)');if(!(await page.locator('#insightBody').innerText()).includes('Resumo'))throw new Error(`detalhes sem resumo em ${id}`);await page.locator('.insight-close').click();}});
await check('configuração de moeda principal',async()=>{await nav('configuracoes');await page.selectOption('#mainCurrency','USD');await page.selectOption('#mainCurrency','BRL');});
await check('responsividade sem loop por 4s',async()=>{await nav('dashboard');const before=Date.now();await page.waitForTimeout(4000);await page.click('#dashboardValueToggle');if(Date.now()-before>7000)throw new Error('interface ficou sem resposta');});
if(pageErrors.length)failures.push(`Erros JS de página: ${pageErrors.join(' | ')}`);
await browser.close();
if(failures.length){console.error('\nAUDITORIA E2E FALHOU');failures.forEach(x=>console.error('- '+x));process.exit(1);}console.log('\nAUDITORIA E2E OK — módulos, recorrências, histórico, dashboard e Firebase executados com conta de teste.');
