import { chromium } from 'playwright';
const BASE='https://paes2005-design.github.io/App_Financas/';
const EMAIL='qa.app.financas.automation@gmail.com', PASSWORD='QaFinancas2026!';
const tag=Date.now().toString().slice(-6), failures=[], pageErrors=[];
const browser=await chromium.launch({headless:true}); const page=await browser.newPage({viewport:{width:1365,height:900}});
page.on('pageerror',e=>pageErrors.push(e.message));
async function check(name,fn){try{await fn();console.log(`PASS ${name}`);}catch(e){failures.push(`${name}: ${e.message}`);console.error(`FAIL ${name}: ${e.message}`);}}
async function vis(s,t=12000){await page.locator(s).waitFor({state:'visible',timeout:t});}
async function nav(id){await page.locator(`.nav-item[data-page="${id}"]`).click();await vis(`#${id}`);}
async function choose(sel,text){await page.waitForFunction(({sel,text})=>[...(document.querySelector(sel)?.options||[])].some(o=>o.textContent.includes(text)),{sel,text},{timeout:12000});const o=page.locator(`${sel} option`).filter({hasText:text}).first();await page.locator(sel).selectOption(await o.getAttribute('value'));}
async function login(){await page.goto(BASE,{waitUntil:'domcontentloaded',timeout:30000});await page.locator('#loading').waitFor({state:'hidden',timeout:15000}).catch(()=>{});if(await page.locator('#appPage').isVisible())return;await vis('#loginPage');await page.fill('#email',EMAIL);await page.fill('#password',PASSWORD);await page.click('#btnCadastrar');await page.waitForTimeout(1500);if(!(await page.locator('#appPage').isVisible())){await page.fill('#email',EMAIL);await page.fill('#password',PASSWORD);await page.click('#btnLogin');}await vis('#appPage',15000);}
async function ensureAccount(name,balance){await nav('contas');if((await page.locator('#listaContas').innerText()).includes(name))return;await page.click('#bankPickerTrigger');await page.locator('.custom-bank-option').click();await page.fill('#contaNomeLivre',name);await page.fill('#contaSaldoInicial',balance);await page.click('#contaForm button[type=submit]');await page.waitForFunction(n=>document.querySelector('#listaContas')?.innerText.includes(n),name,{timeout:12000});}
async function ensureCategory(){await nav('categorias');if((await page.locator('#categoryList').innerText()).includes('QA Geral'))return;await page.selectOption('#categoryOperation','todos');await page.fill('#categoryName','QA Geral');await page.fill('#categorySubcategories','Teste, Assinatura');await page.click('#categorySubmit');await page.waitForFunction(()=>document.querySelector('#categoryList')?.innerText.includes('QA Geral'),{timeout:12000});}
async function logForm(prefix){console.log(prefix,await page.evaluate(p=>({data:document.querySelector(`#${p}Data`)?.value,valor:document.querySelector(`#${p}Valor`)?.value,conta:document.querySelector(`#${p}Conta`)?.value,categoria:document.querySelector(`#${p}Categoria`)?.value,msg:document.querySelector(`#${p}Mensagem`)?.textContent}),prefix));}

await check('autenticação/criação da conta de teste',login);
await check('navegação em todos os 11 módulos',async()=>{for(const id of ['dashboard','contas','receitas','despesas','transferencias','cartoes','categorias','orcamentos','objetivos','relatorios','configuracoes'])await nav(id);});
await check('busca visual de bancos',async()=>{await nav('contas');await page.click('#bankPickerTrigger');await page.fill('#bankSearch','BTG');await vis('.bank-option[data-bank-id="btg"]');await page.click('.bank-option[data-bank-id="btg"]');});
await check('criar/ler contas de teste',async()=>{await ensureAccount('QA Conta A','1000,00');await ensureAccount('QA Conta B','500,00');});
await page.reload({waitUntil:'domcontentloaded'});await page.locator('#loading').waitFor({state:'hidden',timeout:15000}).catch(()=>{});await vis('#appPage',15000);
await check('categorias e subcategorias',ensureCategory);

await check('receita prevista + menu ⋮ + efetivar',async()=>{await nav('receitas');await choose('#receitaConta','QA Conta A');await choose('#receitaCategoria','QA Geral');await page.fill('#receitaDescricao',`QA Receita ${tag}`);await page.fill('#receitaValor','123,45');await logForm('receita');await page.click('#salvarReceita');await page.waitForTimeout(1500);console.log('receita msg/lista',await page.locator('#receitaMensagem').innerText(),await page.locator('#listaReceitas').innerText());await page.waitForFunction(t=>document.querySelector('#listaReceitas')?.innerText.includes(t),`QA Receita ${tag}`,{timeout:10000});const item=page.locator('.transaction-item').filter({hasText:`QA Receita ${tag}`});await item.locator('.txn-more').click();const menu=item.locator('.txn-menu.open');if(!(await menu.innerText()).includes('Efetivar'))throw new Error('menu ⋮ não oferece Efetivar');await menu.getByText('Efetivar').click();await vis('#settlementModal');page.once('dialog',d=>d.accept());await page.click('#settlementModal .settlement-confirm');await page.waitForTimeout(1200);});

await check('despesa prevista + recorrência + menu ⋮',async()=>{await nav('despesas');await choose('#despesaConta','QA Conta A');await choose('#despesaCategoria','QA Geral');await page.fill('#despesaDescricao',`QA Despesa ${tag}`);await page.fill('#despesaValor','45,67');if(await page.locator('#despesaRecorrencia').count())await page.selectOption('#despesaRecorrencia','unica');await page.click('#salvarDespesa');await page.waitForTimeout(1200);console.log('despesa msg',await page.locator('#despesaMensagem').innerText());await page.waitForFunction(t=>document.querySelector('#listaDespesas')?.innerText.includes(t),`QA Despesa ${tag}`,{timeout:10000});const item=page.locator('.expense-item').filter({hasText:`QA Despesa ${tag}`});await item.locator('.txn-more').click();if(!(await item.locator('.txn-menu.open').innerText()).includes('Editar'))throw new Error('menu ⋮ sem Editar');});

await check('transferência prevista entre contas',async()=>{await nav('transferencias');await choose('#transferOrigem','QA Conta A');await choose('#transferDestino','QA Conta B');await choose('#transferCategoria','QA Geral');await page.fill('#transferDescricao',`QA Transfer ${tag}`);await page.fill('#transferValor','10,00');await page.click('#transferSalvar');await page.waitForTimeout(1200);console.log('transfer msg',await page.locator('#transferMensagem').innerText());await page.waitForFunction(t=>document.querySelector('#listaTransferencias')?.innerText.includes(t),`QA Transfer ${tag}`,{timeout:10000});});

await check('cartões criar/editar/excluir',async()=>{await nav('cartoes');await page.fill('#cardNome',`QA Card ${tag}`);await choose('#cardConta','QA Conta A');await page.waitForFunction(()=>document.querySelector('#cardMoeda')?.options.length>0,{timeout:10000});await page.fill('#cardLimite','1500,00');await page.fill('#cardFechamento','20');await page.fill('#cardVencimento','28');await page.click('#cardSalvar');await page.waitForFunction(t=>document.querySelector('#listaCartoes')?.innerText.includes(t),`QA Card ${tag}`,{timeout:10000});const c=page.locator('.credit-card-item').filter({hasText:`QA Card ${tag}`});await c.locator('.edit-card').click();await vis('#cardCancelar');await page.click('#cardCancelar');page.once('dialog',d=>d.accept());await c.locator('.delete-card').click();});

await check('dashboard: ocultar valores, configurações, mês e gráficos',async()=>{await nav('dashboard');await vis('#saldoTotal');await page.click('#dashboardValueToggle');await page.click('#dashboardValueToggle');await page.click('.dashboard-settings-button');await vis('.dashboard-settings-panel');await page.click('.dashboard-settings-back');const a=await page.locator('#dashboardMonthNavigator [data-month-label]').innerText();await page.click('#dashboardMonthNavigator [data-month-prev]');const b=await page.locator('#dashboardMonthNavigator [data-month-label]').innerText();if(a===b)throw new Error('mês não mudou');await page.click('#dashboardMonthNavigator [data-month-current]');for(const id of ['chart-cashChart','chart-compareChart','chart-categoryChart'])if(!(await page.locator(`#${id}`).count()))throw new Error(`gráfico ausente: ${id}`);});
await check('filtros em receitas/despesas/transferências',async()=>{for(const id of ['receitas','despesas','transferencias']){await nav(id);await page.locator(`#${id} .filter-launch`).click();await vis('.filter-modal:not(.hidden)');await page.locator('.filter-modal:not(.hidden) [data-period]').selectOption('custom');await page.locator('.filter-modal:not(.hidden) .filter-close').click();}});
await check('detalhes informativos',async()=>{for(const id of ['receitas','despesas','transferencias']){await nav(id);const b=page.locator(`[data-insight-open="${id}"]`);await b.click();await vis('.insight-modal:not(.hidden)');if(!(await page.locator('#insightBody').innerText()).includes('Resumo'))throw new Error(`detalhes sem resumo em ${id}`);await page.locator('.insight-close').click();}});
await check('configuração de moeda principal',async()=>{await nav('configuracoes');await page.selectOption('#mainCurrency','USD');await page.selectOption('#mainCurrency','BRL');});
await check('responsividade sem loop por 4s',async()=>{await nav('dashboard');const before=Date.now();await page.waitForTimeout(4000);await page.click('#dashboardValueToggle');if(Date.now()-before>7000)throw new Error('interface ficou sem resposta');});
if(pageErrors.length)failures.push(`Erros JS de página: ${pageErrors.join(' | ')}`);
await browser.close();
if(failures.length){console.error('\nAUDITORIA E2E FALHOU');failures.forEach(x=>console.error('- '+x));process.exit(1);}console.log('\nAUDITORIA E2E OK — módulos e fluxos principais executados com conta Firebase de teste.');
